use std::borrow::Cow;

use super::*;

mod cascade;
pub(crate) use self::cascade::*;
mod shorthands;
pub(in crate::css) use self::shorthands::*;
mod box_model;
pub(in crate::css) use self::box_model::*;
mod borders;
pub(in crate::css) use self::borders::*;
mod grid;
pub(in crate::css) use self::grid::*;
mod multicol;
pub(in crate::css) use self::multicol::*;
mod flex;
pub(in crate::css) use self::flex::*;
mod alignment;
pub(in crate::css) use self::alignment::*;
mod defaults;
pub(crate) use self::defaults::*;
mod apply;
pub(crate) use self::apply::*;
mod logical;
pub(in crate::css) use self::logical::*;
mod generated_content;
pub(in crate::css) use self::generated_content::*;
mod syntax;
pub(in crate::css) use self::syntax::*;
mod tables;
pub(in crate::css) use self::tables::*;
mod overflow;
pub(in crate::css) use self::overflow::*;
mod effects;
pub(crate) use self::effects::*;
mod typography;
pub(in crate::css) use self::typography::*;
mod marker;
pub(crate) use self::marker::*;
