use super::*;

#[derive(Debug, Clone)]
pub(in crate::layout) struct RangedMeasuredMixedInlineLineItem {
    pub(in crate::layout) item: MeasuredInlineItem,
    pub(in crate::layout) range: std::ops::Range<usize>,
}

pub(in crate::layout) fn mixed_inline_line_needs_bidi_ordering<T>(
    items: &[T],
    block_style: &ComputedStyle,
) -> bool
where
    T: AsRef<InlineLineItem>,
{
    block_style.direction == Direction::Rtl
        || inline_bidi_scope_affects_line_ordering(block_style)
        || items.iter().any(|item| match item.as_ref() {
            InlineLineItem::Fragment(fragment) => {
                contains_bidi_text(fragment.text())
                    || inline_bidi_scope_affects_line_ordering(fragment.style())
            }
            InlineLineItem::Atom(atom) => {
                atom.style().direction != block_style.direction
                    || inline_bidi_scope_affects_line_ordering(atom.style())
            }
            InlineLineItem::Float(_) => false,
        })
}

pub(in crate::layout) fn graph_remaining_allows_last_hanging_punctuation(
    graph: &InlineOpportunityGraph,
    position: InlineGraphPosition,
) -> bool {
    let Some(run_range) = graph.run_indices_for_graph_range(InlineGraphRange {
        start: position,
        end: graph.end_position(),
    }) else {
        return true;
    };
    run_range.into_iter().all(|run_index| {
        let run = &graph.runs[run_index];
        match &run.item {
            InlineLineItem::Fragment(fragment) => {
                let start = if run_index == position.run_index {
                    position.byte_offset.min(fragment.text().len())
                } else {
                    0
                };
                fragment
                    .text()
                    .get(start..)
                    .is_none_or(|text| text.chars().all(is_css_collapsible_whitespace))
            }
            InlineLineItem::Atom(atom) => atom.content().is_box_edge(),
            InlineLineItem::Float(_) => false,
        }
    })
}

/// Return whether the suffix after an inline float marker has no visible
/// content that must validate the same-line float placement.
///
/// CSS 2.2 float positioning rule 6 prevents a float from being higher than a
/// line box containing an earlier source-order box. If visible suffix content
/// cannot stay on the same line as a tentatively placed inline float, the
/// marker must roll back and be placed on the next line instead of leaving the
/// float attached to the earlier line:
/// <https://www.w3.org/TR/CSS22/visuren.html#float-position>.
pub(in crate::layout) fn graph_remaining_after_position_is_trimmable(
    graph: &InlineOpportunityGraph,
    position: InlineGraphPosition,
) -> bool {
    let Some(run_range) = graph.run_indices_for_graph_range(InlineGraphRange {
        start: position,
        end: graph.end_position(),
    }) else {
        return true;
    };
    run_range.into_iter().all(|run_index| {
        let run = &graph.runs[run_index];
        match &run.item {
            InlineLineItem::Fragment(fragment) => {
                let start = if run_index == position.run_index {
                    position.byte_offset.min(fragment.text().len())
                } else {
                    0
                };
                fragment
                    .text()
                    .get(start..)
                    .is_none_or(|text| inline_suffix_text_is_trimmable(text, fragment))
            }
            InlineLineItem::Atom(atom) => atom.content().is_box_edge(),
            InlineLineItem::Float(_) => false,
        }
    })
}

pub(in crate::layout) fn inline_suffix_text_is_trimmable(
    text: &str,
    fragment: &InlineFragment,
) -> bool {
    text.chars().all(is_css_collapsible_whitespace)
        || (fragment.style().white_space == WhiteSpace::PreWrap
            && text.chars().all(is_css_preserved_document_space))
}

/// Carry a selected line boundary over adjacent zero-width float markers.
///
/// CSS 2.2 says a float generated by an element in the current line is placed
/// with the top of that line box, subject to the remaining float rules. Keeping
/// the marker in the selected range lets the inline float placement path make
/// that decision instead of treating the boundary before the marker as a real
/// content break:
/// <https://www.w3.org/TR/CSS22/visuren.html#floats>.
pub(in crate::layout) fn line_end_extended_over_adjacent_inline_float_markers(
    graph: &InlineOpportunityGraph,
    mut end: InlineGraphPosition,
) -> InlineGraphPosition {
    while end.byte_offset == 0
        && end.run_index < graph.runs.len()
        && matches!(graph.runs[end.run_index].item, InlineLineItem::Float(_))
        && graph.runs[end.run_index].width.abs() <= INLINE_FLOAT_EPSILON
    {
        end = InlineGraphPosition::at_run_start(end.run_index + 1);
    }
    end
}

pub(in crate::layout) fn mixed_measured_inline_line_bidi_text(
    items: &[MeasuredInlineItem],
) -> (String, Vec<RangedMeasuredMixedInlineLineItem>) {
    let mut text = String::new();
    let mut ranged = Vec::new();
    for item in items {
        let start = text.len();
        match &item.item {
            InlineLineItem::Fragment(fragment) => text.push_str(fragment.text()),
            InlineLineItem::Atom(atom) => {
                if mixed_inline_atom_participates_in_bidi_ordering(atom) {
                    text.push(OBJECT_REPLACEMENT_CHARACTER);
                }
            }
            InlineLineItem::Float(_) => {}
        }
        let end = text.len();
        ranged.push(RangedMeasuredMixedInlineLineItem {
            item: item.clone(),
            range: start..end,
        });
    }
    (text, ranged)
}

pub(in crate::layout) fn mixed_inline_atom_participates_in_bidi_ordering(
    atom: &InlineAtom,
) -> bool {
    !matches!(
        atom.content(),
        InlineAtomContent::Leader(_) | InlineAtomContent::InlineEdge(InlineEdgeRole::BoxEdge(_))
    )
}

pub(in crate::layout) fn measured_item_is_transparent_mixed_inline_box_edge(
    item: &MeasuredInlineItem,
) -> bool {
    matches!(
        &item.item,
        InlineLineItem::Atom(atom)
            if matches!(atom.content(), InlineAtomContent::InlineEdge(InlineEdgeRole::BoxEdge(_)))
    )
}

/// Split UBA visual ranges at transparent inline box edge boundaries.
///
/// CSS Writing Modes applies bidi reordering to inline text, while CSS 2.2
/// keeps non-replaced inline box start/end margin, padding, and border at the
/// inline box's own edges. Quire models those edges as transparent atoms so
/// they do not become UAX #9 object replacements, then reinserts them around
/// visual text slices. A single UBA visual run can still contain multiple
/// sibling inline boxes, so split at owned zero-width box-edge boundaries
/// before edge reinsertion; `box-decoration-break: slice` then leaves start
/// and end decoration ownership on the adjacent generated inline box fragment.
/// <https://www.w3.org/TR/css-writing-modes-4/#bidi-algo>,
/// <https://www.w3.org/TR/CSS22/visuren.html#inline-boxes>, and
/// <https://www.w3.org/TR/css-break-3/#break-decoration>.
pub(in crate::layout) fn split_mixed_inline_visual_ranges_at_box_edges(
    visual_ranges: Vec<std::ops::Range<usize>>,
    ranged_items: &[RangedMeasuredMixedInlineLineItem],
    text: &str,
) -> Vec<std::ops::Range<usize>> {
    if visual_ranges.is_empty() {
        return visual_ranges;
    }

    let mut edge_boundaries = ranged_items
        .iter()
        .filter(|ranged| {
            ranged.range.start == ranged.range.end
                && measured_item_is_transparent_mixed_inline_box_edge(&ranged.item)
                && text.is_char_boundary(ranged.range.start)
        })
        .map(|ranged| ranged.range.start)
        .collect::<Vec<_>>();
    edge_boundaries.sort_unstable();
    edge_boundaries.dedup();

    if edge_boundaries.is_empty() {
        return visual_ranges;
    }

    let mut split_ranges = Vec::with_capacity(visual_ranges.len());
    for visual_range in visual_ranges {
        let mut start = visual_range.start;
        for boundary in edge_boundaries
            .iter()
            .copied()
            .filter(|boundary| visual_range.start < *boundary && *boundary < visual_range.end)
        {
            split_ranges.push(start..boundary);
            start = boundary;
        }
        split_ranges.push(start..visual_range.end);
    }
    split_ranges
}

pub(in crate::layout) fn mixed_inline_box_edge_precedes_visual_content(
    item: &MeasuredInlineItem,
) -> Option<bool> {
    let InlineLineItem::Atom(atom) = &item.item else {
        return None;
    };
    let InlineAtomContent::InlineEdge(InlineEdgeRole::BoxEdge(edge)) = atom.content() else {
        return None;
    };
    Some(match edge.physical_side {
        PhysicalSide::Left => true,
        PhysicalSide::Right => false,
        PhysicalSide::Top | PhysicalSide::Bottom => {
            matches!(edge.logical_edge, InlineLogicalEdge::Start)
        }
    })
}

pub(in crate::layout) fn reconcile_mixed_inline_fragment_edge_ownership(
    items: &mut [MeasuredInlineItem],
) {
    let mut keep = Vec::<(usize, InlineLogicalEdge)>::new();
    let mut edge_styles = Vec::<(ComputedStyle, InlineLogicalEdge)>::new();

    for (edge_index, item) in items.iter().enumerate() {
        let Some((style, edge)) = measured_mixed_inline_box_edge_style(item) else {
            continue;
        };
        edge_styles.push((style.clone(), edge.logical_edge));
        if let Some(fragment_index) =
            adjacent_fragment_index_for_visual_edge(items, edge_index, style, edge.logical_edge)
        {
            keep.push((fragment_index, edge.logical_edge));
        }
    }

    if edge_styles.is_empty() {
        return;
    }

    for (fragment_index, item) in items.iter_mut().enumerate() {
        let InlineLineItem::Fragment(fragment) = &mut item.item else {
            continue;
        };
        if fragment.hanging_edges().blocks_start
            && edge_styles.iter().any(|(style, edge)| {
                *edge == InlineLogicalEdge::Start && *style == *fragment.style()
            })
            && !keep.contains(&(fragment_index, InlineLogicalEdge::Start))
        {
            let mut hanging_edges = fragment.hanging_edges();
            hanging_edges.blocks_start = false;
            *fragment = fragment.clone().with_hanging_edges(hanging_edges);
        }
        if fragment.hanging_edges().blocks_end
            && edge_styles
                .iter()
                .any(|(style, edge)| *edge == InlineLogicalEdge::End && *style == *fragment.style())
            && !keep.contains(&(fragment_index, InlineLogicalEdge::End))
        {
            let mut hanging_edges = fragment.hanging_edges();
            hanging_edges.blocks_end = false;
            *fragment = fragment.clone().with_hanging_edges(hanging_edges);
        }
    }
}

pub(in crate::layout) fn measured_mixed_inline_box_edge_style(
    item: &MeasuredInlineItem,
) -> Option<(&ComputedStyle, InlineBoxEdgeFragment)> {
    let InlineLineItem::Atom(atom) = &item.item else {
        return None;
    };
    let InlineAtomContent::InlineEdge(InlineEdgeRole::BoxEdge(edge)) = atom.content() else {
        return None;
    };
    Some((atom.style(), *edge))
}

pub(in crate::layout) fn adjacent_fragment_index_for_visual_edge(
    items: &[MeasuredInlineItem],
    edge_index: usize,
    edge_style: &ComputedStyle,
    edge: InlineLogicalEdge,
) -> Option<usize> {
    match edge {
        InlineLogicalEdge::Start => adjacent_fragment_index_in_visual_edge_candidates(
            items.iter().enumerate().skip(edge_index + 1),
            edge_style,
            edge,
        ),
        InlineLogicalEdge::End => adjacent_fragment_index_in_visual_edge_candidates(
            items[..edge_index].iter().enumerate().rev(),
            edge_style,
            edge,
        ),
    }
}

pub(in crate::layout) fn adjacent_fragment_index_in_visual_edge_candidates<'a>(
    candidates: impl Iterator<Item = (usize, &'a MeasuredInlineItem)>,
    edge_style: &ComputedStyle,
    edge: InlineLogicalEdge,
) -> Option<usize> {
    for (index, item) in candidates {
        match &item.item {
            InlineLineItem::Fragment(fragment) => {
                if *fragment.style() != *edge_style {
                    return None;
                }
                let paints_edge = match edge {
                    InlineLogicalEdge::Start => fragment.hanging_edges().blocks_start,
                    InlineLogicalEdge::End => fragment.hanging_edges().blocks_end,
                };
                return paints_edge.then_some(index);
            }
            InlineLineItem::Atom(atom) if atom.content().is_box_edge() => {}
            InlineLineItem::Atom(_) | InlineLineItem::Float(_) => return None,
        }
    }
    None
}

pub(in crate::layout) fn normalize_mixed_inline_visual_ranges(
    text: &str,
    visual_ranges: Vec<std::ops::Range<usize>>,
) -> Vec<std::ops::Range<usize>> {
    if text.is_empty() {
        return Vec::new();
    }
    let mut ranges = visual_ranges
        .into_iter()
        .filter(|range| {
            range.start < range.end
                && range.end <= text.len()
                && text.is_char_boundary(range.start)
                && text.is_char_boundary(range.end)
        })
        .collect::<Vec<_>>();
    if ranges.is_empty() {
        ranges.push(0..text.len());
    }

    for gap in uncovered_non_bidi_control_text_ranges(text, &ranges) {
        attach_uncovered_visual_range(&mut ranges, gap);
    }
    ranges
}

pub(in crate::layout) fn uncovered_non_bidi_control_text_ranges(
    text: &str,
    ranges: &[std::ops::Range<usize>],
) -> Vec<std::ops::Range<usize>> {
    let mut gaps = Vec::new();
    let mut current_start = None;
    let mut current_end = 0usize;
    for (start, character) in text.char_indices() {
        let end = start + character.len_utf8();
        let covered = character_is_bidi_format_control(character)
            || ranges
                .iter()
                .any(|range| range.start <= start && end <= range.end);
        if covered {
            if let Some(gap_start) = current_start.take() {
                gaps.push(gap_start..current_end);
            }
        } else {
            current_start.get_or_insert(start);
            current_end = end;
        }
    }
    if let Some(gap_start) = current_start {
        gaps.push(gap_start..current_end);
    }
    gaps
}

pub(in crate::layout) fn attach_uncovered_visual_range(
    ranges: &mut Vec<std::ops::Range<usize>>,
    gap: std::ops::Range<usize>,
) {
    if let Some(range) = ranges.iter_mut().find(|range| range.start == gap.end) {
        range.start = gap.start;
        return;
    }
    if let Some(range) = ranges.iter_mut().find(|range| range.end == gap.start) {
        range.end = gap.end;
        return;
    }
    let Some((index, before)) = nearest_visual_range_for_gap(ranges, &gap) else {
        ranges.push(gap);
        return;
    };
    if before {
        ranges.insert(index, gap);
    } else {
        ranges.insert(index + 1, gap);
    }
}

pub(in crate::layout) fn nearest_visual_range_for_gap(
    ranges: &[std::ops::Range<usize>],
    gap: &std::ops::Range<usize>,
) -> Option<(usize, bool)> {
    ranges
        .iter()
        .enumerate()
        .map(|(index, range)| {
            let before_distance = range.start.abs_diff(gap.end);
            let after_distance = range.end.abs_diff(gap.start);
            if before_distance <= after_distance {
                (index, true, before_distance)
            } else {
                (index, false, after_distance)
            }
        })
        .min_by_key(|(_, _, distance)| *distance)
        .map(|(index, before, _)| (index, before))
}

/// Return whether an item starts with punctuation that CSS Text keeps off line start.
///
/// UAX #14 LB13 and CSS Text tailoring suppress line breaks before commas,
/// stops, closing punctuation, and matching quote/bracket categories. Mixed
/// inline layout uses this when inline box edge atoms would otherwise hide the
/// text boundary from the segmenter:
/// <https://www.unicode.org/reports/tr14/#LB13> and
/// <https://www.w3.org/TR/css-text-3/#line-breaking>.
pub(in crate::layout) fn mixed_inline_item_starts_with_suppressed_line_start_punctuation(
    item: &InlineLineItem,
) -> bool {
    let InlineLineItem::Fragment(fragment) = item else {
        return false;
    };
    let Some(character) = fragment
        .text()
        .chars()
        .find(|character| !is_css_collapsible_whitespace(*character))
    else {
        return false;
    };
    character_is_hangable_stop_or_comma(character)
        || character_is_last_hangable_punctuation(character)
}
