use super::*;

/// Input geometry for an abspos grid child's static-position calculation.
///
/// CSS Grid derives the static position of an absolutely positioned child
/// from the grid container and the child's grid-placement properties:
/// <https://www.w3.org/TR/css-grid-1/#abspos-items>.
pub(super) struct PositionedGridStaticContext<'a> {
    pub(super) container_style: &'a ComputedStyle,
    pub(super) stylesheets: &'a [Stylesheet],
    pub(super) inner_x: f32,
    pub(super) inner_width: f32,
    pub(super) content_top: f32,
    pub(super) definite_content_height: Option<f32>,
    pub(super) content_height: f32,
    pub(super) column_line_offsets: &'a [f32],
    pub(super) row_line_offsets: &'a [f32],
    pub(super) establishes_positioning_containing_block: bool,
}

/// Final grid geometry made available while replaying grid contents.
///
/// An absolutely positioned descendant whose containing block is generated by
/// this grid container is grid-positioned even when it is not a direct child.
/// The scope owns the final line geometry so that this late positioned-layout
/// decision never has to recreate or partially rerun grid layout:
/// <https://www.w3.org/TR/css-grid-1/#abspos>.
#[derive(Debug, Clone)]
pub(in crate::layout) struct GridPositioningScope {
    container_style: ComputedStyle,
    inner_x: f32,
    inner_width: f32,
    content_top: f32,
    content_height: f32,
    column_line_offsets: Vec<f32>,
    row_line_offsets: Vec<f32>,
    containing_block: ContainingBlock,
}

/// The late-positioned-layout inputs selected from a grid positioning scope.
/// The containing-block identity is checked before this context is created.
/// An explicitly selected grid area supplies the positioned box's containing
/// block; otherwise the grid container remains its CSS containing block and
/// the scope supplies only the static-position rectangle.
#[derive(Debug, Clone, Copy)]
pub(in crate::layout) struct GridPositionedDescendantContext {
    /// The actual CSS containing block selected by Grid for a qualifying
    /// positioned descendant. The static-position rectangle remains a
    /// separate value below.
    pub(in crate::layout) grid_area_containing_block: Option<ContainingBlock>,
    pub(in crate::layout) static_position: AbsoluteStaticPosition,
}

impl GridPositioningScope {
    pub(super) fn new(
        container_style: &ComputedStyle,
        geometry: GridPositioningGeometry<'_>,
        containing_block: ContainingBlock,
    ) -> Self {
        Self {
            container_style: container_style.clone(),
            inner_x: geometry.inner_x,
            inner_width: geometry.inner_width,
            content_top: geometry.content_top,
            content_height: geometry.content_height,
            column_line_offsets: geometry.column_line_offsets.to_vec(),
            row_line_offsets: geometry.row_line_offsets.to_vec(),
            containing_block,
        }
    }

    /// Return a grid-derived static-position rectangle for a descendant only
    /// when this grid remains its actual absolute containing block.
    pub(in crate::layout) fn descendant_positioning_context(
        &self,
        style: &ComputedStyle,
        containing_block: ContainingBlock,
    ) -> Option<GridPositionedDescendantContext> {
        (containing_block == self.containing_block).then(|| {
            let x = grid_static_line_offset(
                &self.container_style.grid_template_columns,
                &self.container_style.grid_auto_columns,
                &style.grid_column_start,
                &self.column_line_offsets,
                self.container_style.column_gap.clone(),
                self.container_style.justify_content,
                self.inner_width,
            );
            let row_size = self.content_height;
            let y = grid_static_line_offset(
                &self.container_style.grid_template_rows,
                &self.container_style.grid_auto_rows,
                &style.grid_row_start,
                &self.row_line_offsets,
                self.container_style.row_gap.clone(),
                self.container_style.align_content,
                row_size,
            );
            let right = grid_static_line_offset(
                &self.container_style.grid_template_columns,
                &self.container_style.grid_auto_columns,
                &style.grid_column_end,
                &self.column_line_offsets,
                self.container_style.column_gap.clone(),
                self.container_style.justify_content,
                self.inner_width,
            );
            let right = match (x, right) {
                // An abspos item with matching explicit start and end lines
                // occupies the following grid track. Resolve that span from
                // the final line geometry rather than exposing a zero-size
                // containing block to positioned layout.
                // <https://www.w3.org/TR/css-grid-1/#abspos-items>
                (Some(start), Some(end)) if (start - end).abs() <= 0.01 => {
                    grid_static_following_line_offset(start, &self.column_line_offsets)
                        .or(Some(end))
                }
                (_, end) => end,
            }
            .or_else(|| {
                grid_static_auto_end_line_offset(
                    x,
                    &style.grid_column_end,
                    &self.column_line_offsets,
                    &self.container_style.grid_template_columns,
                    self.container_style.justify_content,
                    self.inner_width,
                )
            })
            .unwrap_or(self.inner_width);
            let bottom = grid_static_line_offset(
                &self.container_style.grid_template_rows,
                &self.container_style.grid_auto_rows,
                &style.grid_row_end,
                &self.row_line_offsets,
                self.container_style.row_gap.clone(),
                self.container_style.align_content,
                row_size,
            );
            let bottom = match (y, bottom) {
                (Some(start), Some(end)) if (start - end).abs() <= 0.01 => {
                    grid_static_following_line_offset(start, &self.row_line_offsets).or(Some(end))
                }
                (_, end) => end,
            }
            .or_else(|| {
                grid_static_auto_end_line_offset(
                    y,
                    &style.grid_row_end,
                    &self.row_line_offsets,
                    &self.container_style.grid_template_rows,
                    self.container_style.align_content,
                    row_size,
                )
            })
            .unwrap_or(row_size);
            let x = x.unwrap_or(0.0);
            let y = y.unwrap_or(0.0);
            let right = right.max(x);
            // Grid line numbers advance in the container's inline direction,
            // whereas the final track offsets are physical left-to-right.
            // Convert the resolved logical column range at the grid-area
            // boundary, before it is exposed as a CSS containing block or
            // static-position rectangle.
            // <https://www.w3.org/TR/css-grid-1/#grid-placement-slot> and
            // <https://www.w3.org/TR/css-writing-modes-4/#direction>
            let flow = WritingModeAxes::new(
                self.container_style.writing_mode,
                self.container_style.direction,
            );
            let (x, right) = if flow.physical_axis(LogicalAxis::Inline) == PhysicalAxis::Horizontal
                && flow.physical_side(LogicalSide::InlineStart) == PhysicalSide::Right
            {
                (self.inner_width - right, self.inner_width - x)
            } else {
                (x, right)
            };
            let left = self.inner_x + x;
            let right = self.inner_x + right;
            let top = self.content_top - y;
            let area = PageTopRect::new(left, top, right - left, (bottom - y).max(0.0));
            let placement_selects_grid_area = !matches!(
                (
                    &style.grid_column_start,
                    &style.grid_column_end,
                    &style.grid_row_start,
                    &style.grid_row_end,
                ),
                (
                    css::GridPlacement::Auto,
                    css::GridPlacement::Auto,
                    css::GridPlacement::Auto,
                    css::GridPlacement::Auto,
                )
            );
            GridPositionedDescendantContext {
                // An explicit grid placement selects the grid area as the
                // descendant's containing block. With all four placement
                // edges automatic, the grid container's padding box remains
                // the containing block and Grid supplies only static geometry.
                // <https://www.w3.org/TR/css-grid-1/#abspos>
                grid_area_containing_block: Some(if placement_selects_grid_area {
                    ContainingBlock::from_page_top_rect(area)
                } else {
                    self.containing_block
                }),
                static_position: AbsoluteStaticPosition::from_page_rect_with_horizontal_outside(
                    left, right, top, true,
                )
                .with_grid_alignment(GridAbsposStaticAlignment::new(area, &self.container_style)),
            }
        })
    }
}

/// Resolve the automatic end edge of an abspos grid area from final line
/// geometry when its start edge was explicitly resolved. A one-track automatic
/// span ends at the next grid line rather than at the grid container edge.
/// <https://www.w3.org/TR/css-grid-1/#grid-placement-slot>
fn grid_static_auto_end_line_offset(
    start: Option<f32>,
    end: &css::GridPlacement,
    line_offsets: &[f32],
    explicit_tracks: &css::GridTrackList,
    content_alignment: css::ContentAlignment,
    container_size: f32,
) -> Option<f32> {
    if !matches!(end, css::GridPlacement::Auto) {
        return None;
    }
    let start = start?;
    grid_static_following_line_offset(start, line_offsets).or_else(|| {
        // The initial implicit grid track is an `auto` track. In a definite
        // grid container, `normal` alignment stretches that track to the
        // available grid space, just as explicit `stretch` does. Taffy's
        // empty-grid result exposes only its first line, so reconstruct that
        // final second line when resolving an abspos one-track automatic
        // span. This is geometry completion, not a replacement containing
        // block for the positioned box.
        // <https://www.w3.org/TR/css-grid-1/#implicit-grids> and
        // <https://www.w3.org/TR/css-align-3/#distribution-stretch>
        (matches!(explicit_tracks, css::GridTrackList::None)
            && line_offsets.len() <= 1
            && start.abs() <= 0.01
            && matches!(
                content_alignment.keyword,
                ContentAlignmentKeyword::Normal | ContentAlignmentKeyword::Stretch
            ))
        .then_some(container_size)
    })
}

fn grid_static_following_line_offset(start: f32, line_offsets: &[f32]) -> Option<f32> {
    line_offsets
        .windows(2)
        .find(|pair| (pair[0] - start).abs() <= 0.01)
        .map(|pair| pair[1])
}

pub(super) struct GridPositioningGeometry<'a> {
    pub(super) inner_x: f32,
    pub(super) inner_width: f32,
    pub(super) content_top: f32,
    pub(super) content_height: f32,
    pub(super) column_line_offsets: &'a [f32],
    pub(super) row_line_offsets: &'a [f32],
}

impl<'a> LayoutBuilder<'a> {
    /// Lay out an absolutely positioned grid child from its grid static position.
    ///
    /// CSS Grid says an absolutely positioned child does not participate in
    /// normal grid layout, but its static-position rectangle is derived from
    /// the grid area it would occupy:
    /// <https://www.w3.org/TR/css-grid-1/#abspos-items>.
    pub(super) fn layout_positioned_grid_child<'grid>(
        &mut self,
        child: &GridChild<'grid>,
        in_flow_children: &[GridChild<'grid>],
        context: PositionedGridStaticContext<'_>,
    ) {
        let hypothetical_child = positioned_grid_static_probe_child(child);
        let mut hypothetical_children = Vec::with_capacity(in_flow_children.len() + 1);
        hypothetical_children.extend_from_slice(in_flow_children);
        hypothetical_children.push(hypothetical_child);
        let mut hypothetical = self
            .compute_grid_layout(
                context.container_style,
                &hypothetical_children,
                context.stylesheets,
                context.inner_width,
                context.definite_content_height,
                GridLayoutPurpose::FinalLayout,
            )
            .and_then(|layout| layout.items.into_iter().nth(in_flow_children.len()))
            .unwrap_or(GridItemLayout::new(
                GridRect::new(
                    GridPoint::new(0.0, 0.0),
                    GridSize::new(context.inner_width, child.style.line_height),
                ),
                None,
            ));
        let column_start = grid_static_line_offset(
            &context.container_style.grid_template_columns,
            &context.container_style.grid_auto_columns,
            &child.style.grid_column_start,
            context.column_line_offsets,
            context.container_style.column_gap.clone(),
            context.container_style.justify_content,
            context.inner_width,
        );
        let column_end = grid_static_line_offset(
            &context.container_style.grid_template_columns,
            &context.container_style.grid_auto_columns,
            &child.style.grid_column_end,
            context.column_line_offsets,
            context.container_style.column_gap.clone(),
            context.container_style.justify_content,
            context.inner_width,
        );
        let column_end = match (column_start, column_end) {
            (Some(start), Some(end)) if (start - end).abs() <= 0.01 => {
                grid_static_following_line_offset(start, context.column_line_offsets).or(Some(end))
            }
            (start, end) => end.or_else(|| {
                grid_static_auto_end_line_offset(
                    start,
                    &child.style.grid_column_end,
                    context.column_line_offsets,
                    &context.container_style.grid_template_columns,
                    context.container_style.justify_content,
                    context.inner_width,
                )
            }),
        };
        if let Some(x) = column_start {
            hypothetical.set_axis_geometry(GridAxis::Column, x, hypothetical.width());
        }
        if let (Some(start), Some(end)) = (column_start, column_end)
            && end >= start
        {
            hypothetical.set_axis_geometry(GridAxis::Column, hypothetical.x(), end - start);
        }
        if matches!(child.style.grid_column_start, css::GridPlacement::Auto)
            && matches!(child.style.grid_column_end, css::GridPlacement::Auto)
        {
            // With both grid lines auto, the abspos static-position
            // rectangle spans the grid container's content box. It is not
            // auto-placed after the in-flow grid items.
            // <https://www.w3.org/TR/css-grid-1/#abspos-items>
            hypothetical.set_axis_geometry(GridAxis::Column, 0.0, context.inner_width);
        }
        if WritingModeAxes::new(
            context.container_style.writing_mode,
            context.container_style.direction,
        )
        .physical_axis(LogicalAxis::Inline)
            == PhysicalAxis::Horizontal
            && WritingModeAxes::new(
                context.container_style.writing_mode,
                context.container_style.direction,
            )
            .physical_side(LogicalSide::InlineStart)
                == PhysicalSide::Right
            && column_start.is_some()
            && column_end.is_some()
        {
            let logical_start = column_start.unwrap_or(0.0);
            let logical_end = column_end.unwrap_or(context.inner_width).max(logical_start);
            hypothetical.set_axis_geometry(
                GridAxis::Column,
                context.inner_width - logical_end,
                logical_end - logical_start,
            );
        }
        let row_container_size = context
            .definite_content_height
            .unwrap_or(context.content_height);
        let row_start = grid_static_line_offset(
            &context.container_style.grid_template_rows,
            &context.container_style.grid_auto_rows,
            &child.style.grid_row_start,
            context.row_line_offsets,
            context.container_style.row_gap.clone(),
            context.container_style.align_content,
            row_container_size,
        );
        let row_end = grid_static_line_offset(
            &context.container_style.grid_template_rows,
            &context.container_style.grid_auto_rows,
            &child.style.grid_row_end,
            context.row_line_offsets,
            context.container_style.row_gap.clone(),
            context.container_style.align_content,
            row_container_size,
        );
        let row_end = match (row_start, row_end) {
            (Some(start), Some(end)) if (start - end).abs() <= 0.01 => {
                grid_static_following_line_offset(start, context.row_line_offsets).or(Some(end))
            }
            (start, end) => end.or_else(|| {
                grid_static_auto_end_line_offset(
                    start,
                    &child.style.grid_row_end,
                    context.row_line_offsets,
                    &context.container_style.grid_template_rows,
                    context.container_style.align_content,
                    row_container_size,
                )
            }),
        };
        if let Some(y) = row_start {
            hypothetical.set_axis_geometry(GridAxis::Row, y, hypothetical.height());
        }
        if let (Some(start), Some(end)) = (row_start, row_end)
            && end >= start
        {
            hypothetical.set_axis_geometry(GridAxis::Row, hypothetical.y(), end - start);
        }
        if matches!(child.style.grid_row_start, css::GridPlacement::Auto)
            && matches!(child.style.grid_row_end, css::GridPlacement::Auto)
        {
            hypothetical.set_axis_geometry(GridAxis::Row, 0.0, row_container_size);
        }

        if !context.establishes_positioning_containing_block {
            hypothetical.set_axis_geometry(GridAxis::Column, 0.0, context.inner_width);
            hypothetical.set_axis_geometry(GridAxis::Row, 0.0, row_container_size);
        }

        if context.establishes_positioning_containing_block
            && WritingModeAxes::new(
                context.container_style.writing_mode,
                context.container_style.direction,
            )
            .swaps_physical_axes()
        {
            // `compute_grid_layout` adapts CSS Grid's logical axes to
            // Taffy's physical x/y tracks. For a positioned grid child whose
            // containing block is that grid area, select its physical area
            // through the same swapped line geometry.
            // <https://www.w3.org/TR/css-writing-modes-4/#abstract-box>
            let x_start = grid_static_line_offset(
                &context.container_style.grid_template_rows,
                &context.container_style.grid_auto_rows,
                &child.style.grid_row_start,
                context.column_line_offsets,
                context.container_style.row_gap.clone(),
                context.container_style.align_content,
                context.inner_width,
            )
            .unwrap_or(0.0);
            let x_end = grid_static_line_offset(
                &context.container_style.grid_template_rows,
                &context.container_style.grid_auto_rows,
                &child.style.grid_row_end,
                context.column_line_offsets,
                context.container_style.row_gap.clone(),
                context.container_style.align_content,
                context.inner_width,
            )
            .unwrap_or(context.inner_width)
            .max(x_start);
            let x = if matches!(
                context.container_style.writing_mode,
                WritingMode::VerticalRl | WritingMode::SidewaysRl
            ) {
                context.inner_width - x_end
            } else {
                x_start
            };
            hypothetical.set_axis_geometry(GridAxis::Column, x, x_end - x_start);
            let y_start = grid_static_line_offset(
                &context.container_style.grid_template_columns,
                &context.container_style.grid_auto_columns,
                &child.style.grid_column_start,
                context.row_line_offsets,
                context.container_style.column_gap.clone(),
                context.container_style.justify_content,
                row_container_size,
            )
            .unwrap_or(0.0);
            let y_end = grid_static_line_offset(
                &context.container_style.grid_template_columns,
                &context.container_style.grid_auto_columns,
                &child.style.grid_column_end,
                context.row_line_offsets,
                context.container_style.column_gap.clone(),
                context.container_style.justify_content,
                row_container_size,
            )
            .unwrap_or(row_container_size)
            .max(y_start);
            let y = if context.container_style.direction == Direction::Rtl {
                row_container_size - y_end
            } else {
                y_start
            };
            hypothetical.set_axis_geometry(GridAxis::Row, y, y_end - y_start);
        }

        apply_grid_abspos_self_alignment(
            &mut hypothetical,
            &child.style,
            context.container_style,
            PercentageBasis::definite(layout_pt(context.inner_width)),
        );

        let static_left = context.inner_x + hypothetical.x();
        // The grid container's padding box remains the CSS containing block,
        // while the grid area supplies static-position and alignment geometry.
        // Keeping those values separate is essential when CSS Positioned
        // Layout chooses the RTL static right side for automatic insets.
        // <https://www.w3.org/TR/css-grid-1/#abspos-items> and
        // <https://www.w3.org/TR/css-position-3/#static-position>
        let static_width = grid_abspos_alignment_axis_metrics(
            &child.style,
            PercentageBasis::definite(layout_pt(context.inner_width)),
            GridAbsposAlignmentAxis::Horizontal,
        )
        .border_size
        .unwrap_or(hypothetical.width());
        let static_top = context.content_top - hypothetical.y();
        let grid_alignment = GridAbsposStaticAlignment::new(
            PageTopRect::new(
                static_left,
                static_top,
                hypothetical.width(),
                hypothetical.height(),
            ),
            context.container_style,
        );
        let static_rect = if context.establishes_positioning_containing_block {
            let containing_block = ContainingBlock::from_page_top_rect(PageTopRect::new(
                static_left,
                static_top,
                hypothetical.width(),
                hypothetical.height(),
            ));
            PositionedChildStaticRect::with_containing_block(
                static_left,
                static_left + static_width,
                static_top,
                containing_block,
            )
        } else {
            PositionedChildStaticRect::new(static_left, static_left + static_width, static_top)
        }
        .with_grid_alignment(grid_alignment);
        self.layout_positioned_formatting_context_child(child, context.stylesheets, static_rect);
    }
}

/// Apply the definite-size portion of Grid abspos self-alignment while the
/// static-position grid area is being constructed. Automatically sized axes
/// are refined later by positioned layout once their used size is known.
/// <https://www.w3.org/TR/css-grid-1/#abspos-items>
fn apply_grid_abspos_self_alignment(
    item: &mut GridItemLayout,
    child_style: &ComputedStyle,
    container_style: &ComputedStyle,
    inline_percentage_basis: PercentageBasis<LayoutLength>,
) {
    let container_axes =
        WritingModeAxes::new(container_style.writing_mode, container_style.direction);
    let horizontal = grid_abspos_alignment_axis_metrics(
        child_style,
        inline_percentage_basis,
        GridAbsposAlignmentAxis::Horizontal,
    );
    if let Some(border_size) = horizontal.border_size {
        let (self_alignment, container_alignment) = if container_axes.swaps_physical_axes() {
            (child_style.align_self, container_style.align_items)
        } else {
            (child_style.justify_self, container_style.justify_items)
        };
        let mut alignment = effective_grid_abspos_alignment(self_alignment, container_alignment);
        if matches!(
            (
                container_axes.swaps_physical_axes(),
                WritingModeAxes::new(child_style.writing_mode, child_style.direction,)
                    .swaps_physical_axes()
            ),
            (true, false)
        ) {
            // `self-start` and `self-end` follow the item's own block axis.
            // <https://drafts.csswg.org/css-align-3/#self-position>
            alignment.keyword = match alignment.keyword {
                SelfAlignmentKeyword::SelfStart => SelfAlignmentKeyword::End,
                SelfAlignmentKeyword::SelfEnd => SelfAlignmentKeyword::Start,
                other => other,
            };
        }
        let x = item.x()
            + grid_abspos_alignment_offset(
                alignment,
                item.width(),
                border_size,
                horizontal.margin_start,
                horizontal.margin_end,
                GridAbsposAlignmentDirection {
                    reverse_start_end: container_axes.physical_start_side(
                        container_axes.logical_axis_for_physical(PhysicalAxis::Horizontal),
                    ) == PhysicalSide::Right,
                    left_right_are_physical: !container_axes.swaps_physical_axes(),
                    fallback_to_logical_start: container_axes.swaps_physical_axes()
                        || container_axes.is_reversed(LogicalAxis::Inline),
                },
            );
        item.set_axis_geometry(GridAxis::Column, x, item.width());
    }
    let vertical = grid_abspos_alignment_axis_metrics(
        child_style,
        inline_percentage_basis,
        GridAbsposAlignmentAxis::Vertical,
    );
    if let Some(border_size) = vertical.border_size {
        let (self_alignment, container_alignment) = if container_axes.swaps_physical_axes() {
            (child_style.justify_self, container_style.justify_items)
        } else {
            (child_style.align_self, container_style.align_items)
        };
        let y = item.y()
            + grid_abspos_alignment_offset(
                effective_grid_abspos_alignment(self_alignment, container_alignment),
                item.height(),
                border_size,
                vertical.margin_start,
                vertical.margin_end,
                GridAbsposAlignmentDirection {
                    reverse_start_end: false,
                    left_right_are_physical: false,
                    fallback_to_logical_start: false,
                },
            );
        item.set_axis_geometry(GridAxis::Row, y, item.height());
    }
}

#[derive(Clone, Copy)]
enum GridAbsposAlignmentAxis {
    Horizontal,
    Vertical,
}

struct GridAbsposAlignmentMetrics {
    border_size: Option<f32>,
    margin_start: f32,
    margin_end: f32,
}

fn grid_abspos_alignment_axis_metrics(
    style: &ComputedStyle,
    percentage_basis: PercentageBasis<LayoutLength>,
    axis: GridAbsposAlignmentAxis,
) -> GridAbsposAlignmentMetrics {
    let (
        specified,
        box_sizing,
        padding_start,
        padding_end,
        border_start,
        border_end,
        margin_start,
        margin_end,
    ) = match axis {
        GridAbsposAlignmentAxis::Horizontal => (
            style.box_values.width.clone(),
            style.box_sizing,
            used_length_percentage(style.box_values.padding.left.clone(), percentage_basis)
                .points(),
            used_length_percentage(style.box_values.padding.right.clone(), percentage_basis)
                .points(),
            used_border_widths(style).left,
            used_border_widths(style).right,
            used_length_percentage_or_auto(style.box_values.margin.left.clone(), percentage_basis)
                .map(|margin| margin.points())
                .unwrap_or(0.0),
            used_length_percentage_or_auto(style.box_values.margin.right.clone(), percentage_basis)
                .map(|margin| margin.points())
                .unwrap_or(0.0),
        ),
        GridAbsposAlignmentAxis::Vertical => (
            style.box_values.height.clone(),
            style.box_sizing,
            used_length_percentage(style.box_values.padding.top.clone(), percentage_basis).points(),
            used_length_percentage(style.box_values.padding.bottom.clone(), percentage_basis)
                .points(),
            used_border_widths(style).top,
            used_border_widths(style).bottom,
            used_length_percentage_or_auto(style.box_values.margin.top.clone(), percentage_basis)
                .map(|margin| margin.points())
                .unwrap_or(0.0),
            used_length_percentage_or_auto(
                style.box_values.margin.bottom.clone(),
                percentage_basis,
            )
            .map(|margin| margin.points())
            .unwrap_or(0.0),
        ),
    };
    let border_size = (!specified.is_auto())
        .then(|| used_length_percentage_or_auto(specified, percentage_basis))
        .flatten()
        .map(|size| {
            let size = size.points();
            if box_sizing == BoxSizing::ContentBox {
                size + padding_start + padding_end + border_start + border_end
            } else {
                size
            }
        });
    GridAbsposAlignmentMetrics {
        border_size,
        margin_start,
        margin_end,
    }
}

fn effective_grid_abspos_alignment(
    self_alignment: css::SelfAlignment,
    container_alignment: css::SelfAlignment,
) -> css::SelfAlignment {
    if self_alignment.keyword == SelfAlignmentKeyword::Auto {
        container_alignment
    } else {
        self_alignment
    }
}

#[derive(Clone, Copy)]
struct GridAbsposAlignmentDirection {
    reverse_start_end: bool,
    left_right_are_physical: bool,
    fallback_to_logical_start: bool,
}

fn grid_abspos_alignment_offset(
    alignment: css::SelfAlignment,
    area_size: f32,
    border_size: f32,
    margin_start: f32,
    margin_end: f32,
    direction: GridAbsposAlignmentDirection,
) -> f32 {
    let free_space = area_size - margin_start - border_size - margin_end;
    // Grid's abspos alignment uses the grid area as its alignment container.
    // `safe` falls back to the logical start *alignment* when the subject
    // overflows that area. Clamping free space while retaining `center` or
    // `end` would instead choose a physical side in reversed writing modes.
    // Default and explicit `unsafe` alignment preserve the requested
    // overflowing center/end position:
    // <https://drafts.csswg.org/css-align-3/#overflow-values>.
    let keyword = if alignment.safety == AlignmentSafety::Safe && free_space < 0.0 {
        SelfAlignmentKeyword::Start
    } else {
        alignment.keyword
    };
    let start = margin_start;
    let end = margin_start + free_space;
    match keyword {
        SelfAlignmentKeyword::Center => margin_start + free_space / 2.0,
        SelfAlignmentKeyword::End
        | SelfAlignmentKeyword::SelfEnd
        | SelfAlignmentKeyword::FlexEnd => {
            if direction.reverse_start_end {
                start
            } else {
                end
            }
        }
        SelfAlignmentKeyword::Start
        | SelfAlignmentKeyword::SelfStart
        | SelfAlignmentKeyword::FlexStart => {
            if direction.reverse_start_end {
                end
            } else {
                start
            }
        }
        // `left` and `right` are physical only on a horizontal
        // `justify-self` axis. On `align-self`, and on a vertical
        // `justify-self` axis, they fall back to logical start.
        // <https://drafts.csswg.org/css-align-3/#self-position>
        SelfAlignmentKeyword::Left if direction.left_right_are_physical => start,
        SelfAlignmentKeyword::Right if direction.left_right_are_physical => end,
        SelfAlignmentKeyword::Left | SelfAlignmentKeyword::Right => {
            if direction.fallback_to_logical_start && direction.reverse_start_end {
                end
            } else {
                start
            }
        }
        // CSS Grid's abspos static-position rules resolve the remaining
        // self-alignment fallbacks to logical start. `normal`, `stretch`, and
        // baseline alignment do not stretch an out-of-flow item, but their
        // static position still follows the container's start side.
        // <https://www.w3.org/TR/css-grid-1/#abspos-items> and
        // <https://drafts.csswg.org/css-align-3/#align-abspos>
        SelfAlignmentKeyword::Auto
        | SelfAlignmentKeyword::Normal
        | SelfAlignmentKeyword::Stretch
        | SelfAlignmentKeyword::Baseline
        | SelfAlignmentKeyword::LastBaseline => {
            if direction.fallback_to_logical_start && direction.reverse_start_end {
                end
            } else {
                start
            }
        }
    }
}

/// Resolve the physical horizontal static position after positioned layout has
/// determined an automatically sized grid item's used border-box width.
///
/// This keeps the grid area as the alignment container without substituting
/// it for the actual CSS containing block used by the absolute inset equation:
/// <https://www.w3.org/TR/css-grid-1/#abspos> and
/// <https://drafts.csswg.org/css-align-3/#abspos-align>.
pub(in crate::layout) fn grid_abspos_late_horizontal_static_position(
    grid: GridAbsposStaticAlignment,
    style: &ComputedStyle,
    containing_block: ContainingBlock,
    border_box_width: f32,
) -> StaticHorizontalPosition {
    let axes = WritingModeAxes::new(grid.writing_mode, grid.direction);
    let (self_alignment, container_alignment) = if axes.swaps_physical_axes() {
        (style.align_self, grid.align_items)
    } else {
        (style.justify_self, grid.justify_items)
    };
    let alignment = effective_grid_abspos_alignment(self_alignment, container_alignment);
    let reverse_start_end = axes
        .physical_start_side(axes.logical_axis_for_physical(PhysicalAxis::Horizontal))
        == PhysicalSide::Right;
    let margin_start = style.margin.left;
    let margin_end = style.margin.right;
    let start = grid.area.x()
        + grid_abspos_alignment_offset(
            alignment,
            grid.area.width(),
            border_box_width,
            margin_start,
            margin_end,
            GridAbsposAlignmentDirection {
                reverse_start_end,
                left_right_are_physical: !axes.swaps_physical_axes(),
                fallback_to_logical_start: axes.swaps_physical_axes(),
            },
        );
    let start_in_containing_block = start - containing_block.x();
    let end_in_containing_block =
        start_in_containing_block + margin_start + border_box_width + margin_end;
    StaticHorizontalPosition::new_unclamped(
        start_in_containing_block,
        containing_block.width() - end_in_containing_block,
    )
}

/// Resolve the physical vertical static position after positioned layout has
/// measured an automatically sized grid item's used border-box height.
///
/// The return value is the physical block-start distance expected by the CSS
/// absolute-position vertical equation.
pub(in crate::layout) fn grid_abspos_late_vertical_static_start(
    grid: GridAbsposStaticAlignment,
    style: &ComputedStyle,
    containing_block: ContainingBlock,
    border_box_height: f32,
) -> f32 {
    let axes = WritingModeAxes::new(grid.writing_mode, grid.direction);
    let (self_alignment, container_alignment) = if axes.swaps_physical_axes() {
        (style.justify_self, grid.justify_items)
    } else {
        (style.align_self, grid.align_items)
    };
    let alignment = effective_grid_abspos_alignment(self_alignment, container_alignment);
    // This is the physical vertical axis.  In horizontal writing modes it is
    // always top-to-bottom; in vertical writing modes it is the inline axis,
    // where direction determines its start edge.
    let reverse_start_end = axes
        .physical_start_side(axes.logical_axis_for_physical(PhysicalAxis::Vertical))
        == PhysicalSide::Bottom;
    let offset = grid_abspos_alignment_offset(
        alignment,
        grid.area.height(),
        border_box_height,
        style.margin.top,
        style.margin.bottom,
        GridAbsposAlignmentDirection {
            reverse_start_end,
            left_right_are_physical: false,
            fallback_to_logical_start: false,
        },
    );
    containing_block.top_y() - grid.area.top_y() + offset
}

/// Resolve a grid static-position line from final layout offsets, then from
/// definite CSS track geometry if final offsets cannot cover the requested
/// line.
///
/// CSS Grid defines an abspos child's static-position rectangle from its grid
/// area. Final line offsets are preferred because they preserve used track
/// sizing, content alignment, and collapsed `auto-fit` tracks:
/// <https://www.w3.org/TR/css-grid-1/#abspos-items>.
fn grid_static_line_offset(
    tracks: &css::GridTrackList,
    auto_tracks: &css::GridAutoTrackList,
    placement: &css::GridPlacement,
    line_offsets: &[f32],
    gap: css::ComputedGap,
    content_alignment: css::ContentAlignment,
    container_size: f32,
) -> Option<f32> {
    let after_explicit_implicit_line = grid_static_placement_is_after_explicit_line(
        tracks,
        auto_tracks,
        placement,
        container_size,
    );
    if after_explicit_implicit_line {
        // The in-flow grid has already materialized this implicit track.
        // Replaying the definite track list would re-run `align-content` on
        // an over-constrained implicit grid and move the used line.
        return grid_layout_line_static_offset_with_inferred_gaps(
            tracks,
            auto_tracks,
            placement,
            line_offsets,
            gap.clone(),
            GridLayoutLineStaticOffsetOptions {
                content_alignment,
                container_size,
                include_inferred_gaps: false,
            },
        )
        .or_else(|| {
            grid_line_static_offset(
                tracks,
                auto_tracks,
                placement,
                gap,
                content_alignment,
                container_size,
            )
        });
    }
    // For fully definite track definitions, reconstruct the line from CSS
    // geometry first. Taffy's detailed track record can omit ordinary gutters
    // even though item placement includes them; using that record directly
    // would place an abspos item at a track's trailing edge instead of the
    // following grid line. Intrinsic and auto-repeat tracks still fall back
    // to the final layout geometry below.
    grid_line_static_offset(
        tracks,
        auto_tracks,
        placement,
        gap.clone(),
        content_alignment,
        container_size,
    )
    .or_else(|| {
        grid_layout_line_static_offset(
            tracks,
            auto_tracks,
            placement,
            line_offsets,
            gap,
            content_alignment,
            container_size,
        )
    })
}

fn grid_static_placement_is_after_explicit_line(
    tracks: &css::GridTrackList,
    auto_tracks: &css::GridAutoTrackList,
    placement: &css::GridPlacement,
    container_size: f32,
) -> bool {
    let css::GridTrackList::Tracks {
        components,
        trailing_names,
    } = tracks
    else {
        return false;
    };
    let Some(line_names) = explicit_grid_line_names(components, trailing_names) else {
        return false;
    };
    grid_line_static_offset_index(placement, &line_names, auto_tracks, container_size)
        .is_some_and(|line_index| line_index > line_names.len() as i32)
}

/// Resolve a grid-line static-position offset from final layout.
///
/// CSS Grid says absolutely positioned grid children do not participate in grid
/// layout, but their static-position rectangle is derived from the grid area.
/// Using the already-computed grid line offsets preserves effects such as
/// collapsed empty `auto-fit` tracks and after-explicit implicit lines already
/// created by in-flow items instead of letting a synthetic abspos probe compute
/// a partial grid:
/// <https://www.w3.org/TR/css-grid-1/#abspos-items> and
/// <https://www.w3.org/TR/css-grid-1/#auto-repeat>.
fn grid_layout_line_static_offset(
    tracks: &css::GridTrackList,
    auto_tracks: &css::GridAutoTrackList,
    placement: &css::GridPlacement,
    line_offsets: &[f32],
    gap: css::ComputedGap,
    content_alignment: css::ContentAlignment,
    container_size: f32,
) -> Option<f32> {
    grid_layout_line_static_offset_with_inferred_gaps(
        tracks,
        auto_tracks,
        placement,
        line_offsets,
        gap,
        GridLayoutLineStaticOffsetOptions {
            content_alignment,
            container_size,
            include_inferred_gaps: true,
        },
    )
}

#[derive(Clone, Copy)]
struct GridLayoutLineStaticOffsetOptions {
    content_alignment: css::ContentAlignment,
    container_size: f32,
    include_inferred_gaps: bool,
}

fn grid_layout_line_static_offset_with_inferred_gaps(
    tracks: &css::GridTrackList,
    auto_tracks: &css::GridAutoTrackList,
    placement: &css::GridPlacement,
    line_offsets: &[f32],
    gap: css::ComputedGap,
    options: GridLayoutLineStaticOffsetOptions,
) -> Option<f32> {
    let css::GridPlacement::Line(_) = placement else {
        return None;
    };
    if grid_track_list_has_auto_repeat(tracks) {
        let auto_repeat_count = simple_fixed_auto_repeat_count(
            grid_track_list_components(tracks)?,
            gap.clone(),
            options.container_size,
        )??;
        let line_names = auto_repeat_explicit_line_names(tracks, auto_repeat_count)?;
        let auto_fill_line_offsets;
        let line_offsets = if grid_track_list_has_auto_fit(tracks) {
            line_offsets
        } else {
            let track_sizes = auto_repeat_explicit_track_sizes(
                tracks,
                auto_repeat_count,
                options.container_size,
            )?;
            let gap =
                definite_grid_gap_size(gap.clone(), layout_pt(options.container_size)).points();
            auto_fill_line_offsets = line_offsets_from_track_sizes(&track_sizes, gap);
            &auto_fill_line_offsets
        };
        let line_index = grid_line_static_offset_index(
            placement,
            &line_names,
            auto_tracks,
            options.container_size,
        )?;
        let line_offsets = auto_repeat_static_line_offsets(
            line_offsets,
            &line_names,
            auto_tracks,
            line_index,
            gap,
            options.container_size,
        )?;
        return content_aligned_grid_line_offset(
            options.content_alignment,
            options.container_size,
            &line_offsets.offsets,
            line_offsets.offset_index(line_index)?,
        );
    };
    let (components, trailing_names) = match tracks {
        css::GridTrackList::Tracks {
            components,
            trailing_names,
        } => (components.as_slice(), trailing_names.as_slice()),
        css::GridTrackList::None | css::GridTrackList::Subgrid { .. } => (&[][..], &[][..]),
    };
    let line_names = explicit_grid_line_names(components, trailing_names)?;
    let line_index = match placement {
        // Final grid geometry has already resolved the implicit tracks that
        // in-flow grid items created. A positive numeric line can therefore
        // use that geometry even when `grid-auto-*` is intrinsically sized and
        // cannot be reconstructed from its computed track definition alone.
        // Negative numeric lines remain relative to the explicit grid.
        css::GridPlacement::Line(line) if line.name.is_none() => {
            let index = line.index?;
            if index > 0 {
                index
            } else {
                explicit_grid_line_index(index, i32::try_from(line_names.len()).ok()?)?
            }
        }
        _ => grid_line_static_offset_index(
            placement,
            &line_names,
            auto_tracks,
            options.container_size,
        )?,
    };
    let offset_index = usize::try_from(line_index - 1).ok()?;
    line_offsets.get(offset_index)?;
    let inferred_offsets;
    let line_offsets = if options.include_inferred_gaps {
        // Some detailed Taffy records expose track breadth accumulation while
        // reporting ordinary gutters separately. Reconstruct line coordinates
        // for those fallback paths. Fully materialized implicit grids above
        // retain their final offsets unchanged.
        let gap = definite_grid_gap_size(gap, layout_pt(options.container_size)).points();
        inferred_offsets = line_offsets
            .iter()
            .enumerate()
            .map(|(index, offset)| *offset + gap * index as f32)
            .collect::<Vec<_>>();
        &inferred_offsets
    } else {
        line_offsets
    };
    content_aligned_grid_line_offset(
        options.content_alignment,
        options.container_size,
        line_offsets,
        offset_index,
    )
}

fn grid_track_list_components(
    tracks: &css::GridTrackList,
) -> Option<&[css::GridTrackListComponent]> {
    let css::GridTrackList::Tracks { components, .. } = tracks else {
        return None;
    };
    Some(components)
}

fn grid_track_list_has_auto_repeat(tracks: &css::GridTrackList) -> bool {
    let css::GridTrackList::Tracks { components, .. } = tracks else {
        return false;
    };
    components.iter().any(grid_track_component_has_auto_repeat)
}

pub(super) fn grid_track_list_has_auto_fit(tracks: &css::GridTrackList) -> bool {
    let css::GridTrackList::Tracks { components, .. } = tracks else {
        return false;
    };
    components.iter().any(grid_track_component_has_auto_fit)
}

fn grid_track_component_has_auto_repeat(component: &css::GridTrackListComponent) -> bool {
    let css::GridTrackListComponent::Repeat(_, repeat) = component else {
        return false;
    };
    matches!(
        repeat.count,
        css::GridRepeatCount::AutoFill | css::GridRepeatCount::AutoFit
    )
}

fn grid_track_component_has_auto_fit(component: &css::GridTrackListComponent) -> bool {
    let css::GridTrackListComponent::Repeat(_, repeat) = component else {
        return false;
    };
    matches!(repeat.count, css::GridRepeatCount::AutoFit)
}

fn auto_repeat_explicit_line_names(
    tracks: &css::GridTrackList,
    auto_repeat_count: u16,
) -> Option<Vec<Vec<String>>> {
    let css::GridTrackList::Tracks {
        components,
        trailing_names,
    } = tracks
    else {
        return None;
    };
    let mut lines = Vec::new();
    let mut current_line_names = Vec::new();
    collect_auto_repeat_line_names(
        components,
        auto_repeat_count,
        &mut current_line_names,
        &mut lines,
    )?;
    current_line_names.extend(trailing_names.iter().cloned());
    lines.push(current_line_names);
    Some(lines)
}

fn auto_repeat_explicit_track_sizes(
    tracks: &css::GridTrackList,
    auto_repeat_count: u16,
    container_size: f32,
) -> Option<Vec<f32>> {
    let components = grid_track_list_components(tracks)?;
    let mut sizes = Vec::new();
    collect_auto_repeat_track_sizes(components, auto_repeat_count, container_size, &mut sizes)?;
    Some(sizes)
}

fn collect_auto_repeat_track_sizes(
    components: &[css::GridTrackListComponent],
    auto_repeat_count: u16,
    container_size: f32,
    sizes: &mut Vec<f32>,
) -> Option<()> {
    for component in components {
        match component {
            css::GridTrackListComponent::Track(_, size) => {
                sizes.push(definite_auto_repeat_track_size(
                    size.clone(),
                    container_size,
                )?);
            }
            css::GridTrackListComponent::Repeat(_, repeat) => {
                let count = match repeat.count {
                    css::GridRepeatCount::Number(count) => count,
                    css::GridRepeatCount::AutoFill | css::GridRepeatCount::AutoFit => {
                        auto_repeat_count
                    }
                };
                for _ in 0..count {
                    collect_auto_repeat_track_sizes(
                        &repeat.tracks,
                        auto_repeat_count,
                        container_size,
                        sizes,
                    )?;
                }
            }
        }
    }
    Some(())
}

fn line_offsets_from_track_sizes(track_sizes: &[f32], gap: f32) -> Vec<f32> {
    let mut offsets = Vec::with_capacity(track_sizes.len() + 1);
    let mut offset = 0.0;
    offsets.push(offset);
    for (index, size) in track_sizes.iter().enumerate() {
        offset += *size;
        if index + 1 < track_sizes.len() {
            offset += gap;
        }
        offsets.push(offset);
    }
    offsets
}

struct AutoRepeatStaticLineOffsets {
    first_line_index: i32,
    offsets: Vec<f32>,
}

impl AutoRepeatStaticLineOffsets {
    fn offset_index(&self, line_index: i32) -> Option<usize> {
        usize::try_from(line_index.checked_sub(self.first_line_index)?).ok()
    }
}

fn auto_repeat_static_line_offsets(
    line_offsets: &[f32],
    line_names: &[Vec<String>],
    auto_tracks: &css::GridAutoTrackList,
    line_index: i32,
    gap: css::ComputedGap,
    container_size: f32,
) -> Option<AutoRepeatStaticLineOffsets> {
    let explicit_line_count = i32::try_from(line_names.len()).ok()?;
    let before_track_count = if line_index < 1 {
        usize::try_from(1_i32.checked_sub(line_index)?).ok()?
    } else {
        0
    };
    let after_track_count = if line_index > explicit_line_count {
        usize::try_from(line_index.checked_sub(explicit_line_count)?).ok()?
    } else {
        0
    };
    let gap = definite_grid_gap_size(gap, layout_pt(container_size)).points();
    if before_track_count == 0 && after_track_count == 0 {
        return Some(AutoRepeatStaticLineOffsets {
            first_line_index: 1,
            offsets: line_offsets.to_vec(),
        });
    }

    let mut offsets = line_offsets.to_vec();
    let mut first_line_index = 1;
    if before_track_count > 0 {
        let mut expanded = Vec::with_capacity(before_track_count + offsets.len());
        let mut offset = 0.0;
        expanded.push(offset);
        for auto_index in (0..before_track_count).rev() {
            offset +=
                cycled_definite_auto_track_size_before(auto_tracks, auto_index, container_size)?;
            offset += gap;
            expanded.push(offset);
        }
        let explicit_start_offset = offset;
        expanded.extend(
            offsets
                .iter()
                .skip(1)
                .map(|line_offset| explicit_start_offset + *line_offset),
        );
        offsets = expanded;
        first_line_index = 1_i32.checked_sub(i32::try_from(before_track_count).ok()?)?;
    }
    if after_track_count > 0 {
        let mut offset = offsets.last().cloned()?;
        for auto_index in 0..after_track_count {
            // A following implicit line is after the preceding gutter and
            // track. The next gutter is before the next implicit track, not
            // part of this line's offset.
            offset += gap;
            offset +=
                cycled_definite_auto_track_size_after(auto_tracks, auto_index, container_size)?;
            offsets.push(offset);
        }
    }
    let result = AutoRepeatStaticLineOffsets {
        first_line_index,
        offsets,
    };
    result
        .offset_index(line_index)
        .and_then(|index| result.offsets.get(index))
        .cloned()?;
    Some(result)
}

fn collect_auto_repeat_line_names(
    components: &[css::GridTrackListComponent],
    auto_repeat_count: u16,
    current_line_names: &mut Vec<String>,
    lines: &mut Vec<Vec<String>>,
) -> Option<()> {
    for component in components {
        match component {
            css::GridTrackListComponent::Track(names, _) => {
                current_line_names.extend(names.iter().cloned());
                lines.push(std::mem::take(current_line_names));
            }
            css::GridTrackListComponent::Repeat(names, repeat) => {
                current_line_names.extend(names.iter().cloned());
                let count = match repeat.count {
                    css::GridRepeatCount::Number(count) => count,
                    css::GridRepeatCount::AutoFill | css::GridRepeatCount::AutoFit => {
                        auto_repeat_count
                    }
                };
                for _ in 0..count {
                    collect_auto_repeat_line_names(
                        &repeat.tracks,
                        auto_repeat_count,
                        current_line_names,
                        lines,
                    )?;
                    current_line_names.extend(repeat.trailing_names.iter().cloned());
                }
            }
        }
    }
    Some(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn numeric_line_static_offset_includes_track_gaps() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![
                css::GridTrackListComponent::Track(
                    Vec::new(),
                    css::GridTrackSize {
                        min: css::GridMinTrackBreadth::LengthPercentage(
                            css::ComputedLengthPercentage::from_points(20.0),
                        ),
                        max: css::GridMaxTrackBreadth::LengthPercentage(
                            css::ComputedLengthPercentage::from_points(20.0),
                        ),
                    },
                ),
                css::GridTrackListComponent::Track(
                    Vec::new(),
                    css::GridTrackSize {
                        min: css::GridMinTrackBreadth::LengthPercentage(
                            css::ComputedLengthPercentage::from_points(20.0),
                        ),
                        max: css::GridMaxTrackBreadth::LengthPercentage(
                            css::ComputedLengthPercentage::from_points(20.0),
                        ),
                    },
                ),
            ],
            trailing_names: Vec::new(),
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: None,
            index: Some(2),
        });
        assert_eq!(
            grid_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                45.0,
            ),
            Some(25.0)
        );
    }

    #[test]
    fn named_line_static_offset_resolves_explicit_line_occurrences() {
        let fixed_track = css::GridTrackSize {
            min: css::GridMinTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
            max: css::GridMaxTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
        };
        let tracks = css::GridTrackList::Tracks {
            components: vec![
                css::GridTrackListComponent::Track(vec!["main".to_string()], fixed_track.clone()),
                css::GridTrackListComponent::Track(vec!["main".to_string()], fixed_track),
            ],
            trailing_names: vec!["main".to_string()],
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: Some("main".to_string()),
            index: Some(2),
        });
        assert_eq!(
            grid_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                45.0,
            ),
            Some(25.0)
        );
    }

    #[test]
    fn negative_numeric_line_static_offset_counts_from_explicit_grid_end() {
        let fixed_track = css::GridTrackSize {
            min: css::GridMinTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
            max: css::GridMaxTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
        };
        let tracks = css::GridTrackList::Tracks {
            components: vec![
                css::GridTrackListComponent::Track(Vec::new(), fixed_track.clone()),
                css::GridTrackListComponent::Track(Vec::new(), fixed_track),
            ],
            trailing_names: Vec::new(),
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: None,
            index: Some(-1),
        });
        assert_eq!(
            grid_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                45.0,
            ),
            Some(45.0)
        );
    }

    #[test]
    fn negative_named_line_static_offset_counts_from_explicit_grid_end() {
        let fixed_track = css::GridTrackSize {
            min: css::GridMinTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
            max: css::GridMaxTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
        };
        let tracks = css::GridTrackList::Tracks {
            components: vec![
                css::GridTrackListComponent::Track(vec!["main".to_string()], fixed_track.clone()),
                css::GridTrackListComponent::Track(vec!["main".to_string()], fixed_track),
            ],
            trailing_names: vec!["main".to_string()],
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: Some("main".to_string()),
            index: Some(-1),
        });
        assert_eq!(
            grid_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                45.0,
            ),
            Some(45.0)
        );
    }

    #[test]
    fn numeric_static_offset_uses_final_collapsed_track_lines() {
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: None,
            index: Some(3),
        });
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFit,
                    tracks: vec![css::GridTrackListComponent::Track(
                        Vec::new(),
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: Vec::new(),
                },
            )],
            trailing_names: Vec::new(),
        };
        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(45.0)
        );
        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::End),
                70.0,
            ),
            Some(70.0)
        );
        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::SpaceBetween),
                70.0,
            ),
            Some(70.0)
        );
        let space_around = grid_layout_line_static_offset(
            &tracks,
            &css::GridAutoTrackList::initial(),
            &placement,
            &[0.0, 25.0, 45.0, 45.0],
            css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0)),
            css::ContentAlignment::new(css::ContentAlignmentKeyword::SpaceAround),
            70.0,
        )
        .unwrap();
        assert!(
            (space_around - 63.75).abs() < 0.001,
            "space-around should add half edge interval plus one between interval: {space_around}"
        );
        let space_evenly = grid_layout_line_static_offset(
            &tracks,
            &css::GridAutoTrackList::initial(),
            &placement,
            &[0.0, 25.0, 45.0, 45.0],
            css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0)),
            css::ContentAlignment::new(css::ContentAlignmentKeyword::SpaceEvenly),
            70.0,
        )
        .unwrap();
        assert!(
            (space_evenly - (45.0 + 25.0 / 3.0 * 2.0)).abs() < 0.001,
            "space-evenly should add one edge interval and one between interval: {space_evenly}"
        );
    }

    #[test]
    fn named_static_offset_expands_final_auto_fit_line_names() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFit,
                    tracks: vec![css::GridTrackListComponent::Track(
                        vec!["slot".to_string()],
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: Some("slot".to_string()),
            index: Some(3),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(45.0)
        );
    }

    #[test]
    fn named_static_offset_expands_final_auto_fill_line_names() {
        let fixed_track = css::GridTrackListComponent::Track(
            vec!["slot".to_string()],
            css::GridTrackSize {
                min: css::GridMinTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(10.0),
                ),
                max: css::GridMaxTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(10.0),
                ),
            },
        );
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFill,
                    tracks: vec![
                        fixed_track,
                        css::GridTrackListComponent::Track(
                            vec!["middle".to_string()],
                            css::GridTrackSize {
                                min: css::GridMinTrackBreadth::LengthPercentage(
                                    css::ComputedLengthPercentage::from_points(10.0),
                                ),
                                max: css::GridMaxTrackBreadth::LengthPercentage(
                                    css::ComputedLengthPercentage::from_points(10.0),
                                ),
                            },
                        ),
                    ],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: Some("middle".to_string()),
            index: Some(2),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                &[0.0, 15.0, 30.0, 45.0, 60.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                60.0,
            ),
            Some(45.0)
        );
    }

    #[test]
    fn named_static_offset_resolves_auto_fill_after_explicit_implicit_line() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFill,
                    tracks: vec![css::GridTrackListComponent::Track(
                        vec!["slot".to_string()],
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let auto_tracks = css::GridAutoTrackList {
            tracks: vec![css::GridTrackSize {
                min: css::GridMinTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(30.0),
                ),
                max: css::GridMaxTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(30.0),
                ),
            }],
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: Some("slot".to_string()),
            index: Some(4),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &auto_tracks,
                &placement,
                &[0.0, 25.0, 50.0, 70.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(105.0)
        );
    }

    #[test]
    fn named_static_offset_resolves_auto_fill_before_explicit_implicit_line() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFill,
                    tracks: vec![css::GridTrackListComponent::Track(
                        vec!["slot".to_string()],
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let auto_tracks = css::GridAutoTrackList {
            tracks: vec![
                css::GridTrackSize {
                    min: css::GridMinTrackBreadth::LengthPercentage(
                        css::ComputedLengthPercentage::from_points(30.0),
                    ),
                    max: css::GridMaxTrackBreadth::LengthPercentage(
                        css::ComputedLengthPercentage::from_points(30.0),
                    ),
                },
                css::GridTrackSize {
                    min: css::GridMinTrackBreadth::LengthPercentage(
                        css::ComputedLengthPercentage::from_points(40.0),
                    ),
                    max: css::GridMaxTrackBreadth::LengthPercentage(
                        css::ComputedLengthPercentage::from_points(40.0),
                    ),
                },
            ],
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: Some("slot".to_string()),
            index: Some(-4),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &auto_tracks,
                &placement,
                &[0.0, 25.0, 50.0, 70.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(0.0)
        );
    }

    #[test]
    fn named_static_offset_resolves_auto_fit_after_explicit_implicit_line() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFit,
                    tracks: vec![css::GridTrackListComponent::Track(
                        vec!["slot".to_string()],
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let auto_tracks = css::GridAutoTrackList {
            tracks: vec![css::GridTrackSize {
                min: css::GridMinTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(30.0),
                ),
                max: css::GridMaxTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(30.0),
                ),
            }],
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: Some("slot".to_string()),
            index: Some(4),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &auto_tracks,
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(80.0)
        );
    }

    #[test]
    fn named_static_offset_resolves_auto_fit_before_explicit_implicit_line() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFit,
                    tracks: vec![css::GridTrackListComponent::Track(
                        vec!["slot".to_string()],
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let auto_tracks = css::GridAutoTrackList {
            tracks: vec![
                css::GridTrackSize {
                    min: css::GridMinTrackBreadth::LengthPercentage(
                        css::ComputedLengthPercentage::from_points(30.0),
                    ),
                    max: css::GridMaxTrackBreadth::LengthPercentage(
                        css::ComputedLengthPercentage::from_points(30.0),
                    ),
                },
                css::GridTrackSize {
                    min: css::GridMinTrackBreadth::LengthPercentage(
                        css::ComputedLengthPercentage::from_points(40.0),
                    ),
                    max: css::GridMaxTrackBreadth::LengthPercentage(
                        css::ComputedLengthPercentage::from_points(40.0),
                    ),
                },
            ],
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement {
            name: Some("slot".to_string()),
            index: Some(-4),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &auto_tracks,
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(0.0)
        );
    }
}
