use super::model::GridAxisTopology;
use super::*;

/// Input geometry for an abspos grid child's static-position calculation.
///
/// CSS Grid derives the static position of an absolutely positioned child
/// from the grid container and the child's grid-placement properties:
/// <https://www.w3.org/TR/css-grid-1/#abspos-items>.
pub(super) struct PositionedGridStaticContext<'a> {
    pub(super) container_style: &'a ComputedStyle,
    pub(super) stylesheets: &'a Stylesheets<'a>,
    pub(super) inner_x: f32,
    pub(super) inner_width: PhysicalContentWidth,
    pub(super) content_top: f32,
    pub(super) definite_content_height: Option<PhysicalContentHeight>,
    pub(super) content_height: PhysicalContentHeight,
    pub(super) columns: &'a GridAxisTopology,
    pub(super) rows: &'a GridAxisTopology,
    pub(super) column_line_offsets: &'a [f32],
    pub(super) row_line_offsets: &'a [f32],
    /// The Grid padding box when this Grid establishes the child's actual
    /// absolute-positioning containing block.
    pub(super) positioning_containing_block: Option<ContainingBlock>,
}

/// The formatting-context source of a Grid child's static-position rectangle.
///
/// A Grid child uses the Grid content edges when its actual containing block
/// is elsewhere. Only a Grid that establishes that actual containing block
/// substitutes the grid-placement area (whose automatic placement edges are
/// the Grid padding edges):
/// <https://www.w3.org/TR/css-position-3/#staticpos-rect> and
/// <https://www.w3.org/TR/css-grid-1/#abspos>.
#[derive(Debug, Clone, Copy)]
enum GridAbsposStaticPositionSource {
    ContentEdges,
    PlacementArea { padding_box: ContainingBlock },
}

/// Final grid geometry made available while replaying grid contents.
///
/// An absolutely positioned descendant whose containing block is generated by
/// this grid container is grid-positioned even when it is not a direct child.
/// The scope owns the final line geometry so that this late positioned-layout
/// decision never has to recreate or partially rerun grid layout:
/// <https://www.w3.org/TR/css-grid-1/#abspos>.
#[derive(Debug, Clone)]
pub(in crate::layout) struct GridPositioningScope {
    container_style: ComputedStyle,
    inner_x: f32,
    inner_width: PhysicalContentWidth,
    content_top: f32,
    content_height: PhysicalContentHeight,
    columns: GridAxisTopology,
    rows: GridAxisTopology,
    containing_block: ContainingBlock,
}

/// The Grid-specific containing-block override for a positioned descendant.
///
/// A Grid container can establish the actual absolute-positioning containing
/// block of a descendant even though that descendant is not a direct Grid
/// child.  In that case Grid placement selects the actual containing block,
/// but the descendant's static-position rectangle remains owned by its
/// intervening ordinary formatting context:
/// <https://www.w3.org/TR/css-grid-1/#abspos> and
/// <https://www.w3.org/TR/css-position-3/#staticpos-rect>.
#[derive(Debug, Clone, Copy)]
pub(in crate::layout) struct GridDescendantContainingBlock {
    /// The actual CSS containing block selected by Grid placement.
    pub(in crate::layout) containing_block: ContainingBlock,
}

/// Resolve the physical rectangle used by Grid to establish a child's static
/// position. The caller has already resolved a placement area from final grid
/// line geometry; this function applies CSS Grid's special automatic
/// placement lines at the Grid padding edges when that placement area is the
/// actual containing block.
fn grid_abspos_static_position_area(
    source: GridAbsposStaticPositionSource,
    placement_area: PageTopRect,
    child_style: &ComputedStyle,
    container_style: &ComputedStyle,
) -> PageTopRect {
    let GridAbsposStaticPositionSource::PlacementArea { padding_box } = source else {
        return placement_area;
    };

    let mut left = placement_area.x();
    let mut right = left + placement_area.width();
    let mut top = placement_area.top_y();
    let mut bottom = placement_area.bottom_y();
    let padding = padding_box.rect;
    let axes = WritingModeAxes::new(
        container_style.writing_mode,
        container_style.used_direction(),
    );
    let mut use_padding_edge = |placement: &css::GridPlacement, side: LogicalSide| {
        if !matches!(placement, css::GridPlacement::Auto) {
            return;
        }
        match axes.physical_side(side) {
            PhysicalSide::Left => left = padding.x(),
            PhysicalSide::Right => right = padding.x() + padding.width(),
            PhysicalSide::Top => top = padding.top_y(),
            PhysicalSide::Bottom => bottom = padding.bottom_y(),
        }
    };
    use_padding_edge(&child_style.grid_column_start, LogicalSide::InlineStart);
    use_padding_edge(&child_style.grid_column_end, LogicalSide::InlineEnd);
    use_padding_edge(&child_style.grid_row_start, LogicalSide::BlockStart);
    use_padding_edge(&child_style.grid_row_end, LogicalSide::BlockEnd);

    PageTopRect::new(
        left.min(right),
        top.max(bottom),
        (right - left).abs(),
        (top - bottom).abs(),
    )
}

/// Convert Grid's selected static-position rectangle into the generic
/// positioned-layout handoff without applying self-alignment early. The
/// generic positioned algorithm owns alignment because it is the first point
/// where the abspos margin-box size is known.
fn grid_positioned_child_static_rect(
    source: GridAbsposStaticPositionSource,
    area: PageTopRect,
    child_style: &ComputedStyle,
    container_style: &ComputedStyle,
) -> PositionedChildStaticRect {
    let left = area.x();
    let right = left + area.width();
    let static_rect = match source {
        GridAbsposStaticPositionSource::ContentEdges => {
            PositionedChildStaticRect::new(left, right, area.top_y())
        }
        GridAbsposStaticPositionSource::PlacementArea { .. } => {
            PositionedChildStaticRect::with_containing_block(
                left,
                right,
                area.top_y(),
                ContainingBlock::from_page_top_rect(area),
            )
        }
    };
    // Grid supplies its own static-position alignment container even for an
    // effective `normal` value.  In particular, `normal` is logical start,
    // not the physical-left fallback used by ordinary block flow; omitting
    // this payload breaks RTL and orthogonal grid children.
    // <https://www.w3.org/TR/css-grid-1/#abspos-items>
    static_rect.with_static_alignment(grid_abspos_static_alignment(
        area,
        child_style,
        container_style,
    ))
}

impl GridPositioningScope {
    pub(super) fn new(
        container_style: &ComputedStyle,
        geometry: GridPositioningGeometry<'_>,
        containing_block: ContainingBlock,
    ) -> Self {
        Self {
            container_style: container_style.clone(),
            inner_x: geometry.inner_x,
            inner_width: geometry.inner_width,
            content_top: geometry.content_top,
            content_height: geometry.content_height,
            columns: geometry.columns.clone(),
            rows: geometry.rows.clone(),
            containing_block,
        }
    }

    /// Return a Grid-derived containing block for a descendant only when this
    /// Grid remains its actual absolute containing block.
    ///
    /// Unlike a direct positioned Grid child, a descendant keeps the ordinary
    /// static-position rectangle captured while its parent formatting context
    /// was replayed.  Grid contributes only the actual containing block here.
    pub(in crate::layout) fn descendant_containing_block(
        &self,
        style: &ComputedStyle,
        containing_block: ContainingBlock,
    ) -> Option<GridDescendantContainingBlock> {
        (containing_block == self.containing_block).then(|| {
            let content_area = PageTopRect::new(
                self.inner_x,
                self.content_top,
                self.inner_width.points(),
                self.content_height.points(),
            );
            // Direct and nested positioned Grid descendants must project the
            // final logical Grid lines through exactly the same writing-mode
            // and direction adapter. In particular, mirroring an RTL column
            // range after resolving physical lines reverses it twice.
            // <https://www.w3.org/TR/css-grid-1/#grid-placement-slot> and
            // <https://www.w3.org/TR/css-writing-modes-4/#logical-to-physical>
            let placement_area = grid_explicit_placement_area(
                &self.container_style,
                style,
                content_area,
                &self.columns,
                &self.rows,
            )
            .unwrap_or(content_area);
            let area = grid_abspos_static_position_area(
                GridAbsposStaticPositionSource::PlacementArea {
                    padding_box: self.containing_block,
                },
                placement_area,
                style,
                &self.container_style,
            );
            let placement_selects_grid_area = !matches!(
                (
                    &style.grid_column_start,
                    &style.grid_column_end,
                    &style.grid_row_start,
                    &style.grid_row_end,
                ),
                (
                    css::GridPlacement::Auto,
                    css::GridPlacement::Auto,
                    css::GridPlacement::Auto,
                    css::GridPlacement::Auto,
                )
            );
            GridDescendantContainingBlock {
                // An explicit grid placement selects the grid area as the
                // descendant's containing block. With all four placement
                // edges automatic, the grid container's padding box remains
                // the containing block and Grid supplies only static geometry.
                // <https://www.w3.org/TR/css-grid-1/#abspos>
                containing_block: if placement_selects_grid_area {
                    ContainingBlock::from_page_top_rect(area)
                } else {
                    self.containing_block
                },
            }
        })
    }
}

/// Resolve the automatic end edge of an abspos grid area from final line
/// geometry when its start edge was explicitly resolved. A one-track automatic
/// span ends at the next grid line rather than at the grid container edge.
/// <https://www.w3.org/TR/css-grid-1/#grid-placement-slot>
fn grid_static_auto_end_line_offset(
    start: Option<f32>,
    end: &css::GridPlacement,
    line_offsets: &[f32],
    explicit_tracks: &css::GridTrackList,
    content_alignment: css::ContentAlignment,
    container_size: f32,
) -> Option<f32> {
    if !matches!(end, css::GridPlacement::Auto) {
        return None;
    }
    let start = start?;
    grid_static_following_line_offset(start, line_offsets).or_else(|| {
        // The initial implicit grid track is an `auto` track. In a definite
        // grid container, `normal` alignment stretches that track to the
        // available grid space, just as explicit `stretch` does. Taffy's
        // empty-grid result exposes only its first line, so reconstruct that
        // final second line when resolving an abspos one-track automatic
        // span. This is geometry completion, not a replacement containing
        // block for the positioned box.
        // <https://www.w3.org/TR/css-grid-1/#implicit-grids> and
        // <https://www.w3.org/TR/css-align-3/#distribution-stretch>
        (matches!(explicit_tracks, css::GridTrackList::None)
            && line_offsets.len() <= 1
            && start.abs() <= 0.01
            && matches!(
                content_alignment.keyword,
                ContentAlignmentKeyword::Normal | ContentAlignmentKeyword::Stretch
            ))
        .then_some(container_size)
    })
}

fn grid_static_following_line_offset(start: f32, line_offsets: &[f32]) -> Option<f32> {
    line_offsets
        .windows(2)
        .find(|pair| (pair[0] - start).abs() <= 0.01)
        .map(|pair| pair[1])
}

/// Resolve the physical Grid area for a child whose four placement edges are
/// explicit grid lines.
///
/// Taffy's final track geometry is stored in physical x/y arrays, while CSS
/// placement always addresses the Grid's logical column/row axes.  Project
/// the selected logical ranges exactly once at this boundary; in particular,
/// a vertical Grid's columns use the final physical-y lines, and RTL reverses
/// only its logical inline axis.
/// <https://www.w3.org/TR/css-grid-1/#grid-placement-slot>
/// <https://www.w3.org/TR/css-writing-modes-4/#abstract-box>
fn grid_explicit_placement_area(
    container_style: &ComputedStyle,
    child_style: &ComputedStyle,
    content_area: PageTopRect,
    columns: &GridAxisTopology,
    rows: &GridAxisTopology,
) -> Option<PageTopRect> {
    let axes = WritingModeAxes::new(
        container_style.writing_mode,
        container_style.used_direction(),
    );
    let (inline_start, inline_end) = grid_static_logical_axis_range(
        LogicalAxis::Inline,
        container_style,
        child_style,
        &axes,
        content_area,
        columns,
        rows,
    )?;
    let (block_start, block_end) = grid_static_logical_axis_range(
        LogicalAxis::Block,
        container_style,
        child_style,
        &axes,
        content_area,
        columns,
        rows,
    )?;

    let mut left = content_area.x();
    let mut right = left + content_area.width();
    let mut top = content_area.top_y();
    let mut bottom = content_area.bottom_y();
    grid_project_logical_range(
        &mut left,
        &mut right,
        &mut top,
        &mut bottom,
        content_area,
        axes.physical_start_side(LogicalAxis::Inline),
        inline_start,
        inline_end,
    );
    grid_project_logical_range(
        &mut left,
        &mut right,
        &mut top,
        &mut bottom,
        content_area,
        axes.physical_start_side(LogicalAxis::Block),
        block_start,
        block_end,
    );
    Some(PageTopRect::new(
        left.min(right),
        top.max(bottom),
        (right - left).abs(),
        (top - bottom).abs(),
    ))
}

/// Resolve one Grid logical placement axis from its final physical track-line
/// offsets. This intentionally accepts only directly resolved start/end lines:
/// spans and missing line geometry continue through the existing hypothetical
/// Grid probe, which is the authoritative fallback for those cases.
fn grid_static_logical_axis_range(
    axis: LogicalAxis,
    container_style: &ComputedStyle,
    child_style: &ComputedStyle,
    axes: &WritingModeAxes,
    content_area: PageTopRect,
    columns: &GridAxisTopology,
    rows: &GridAxisTopology,
) -> Option<(f32, f32)> {
    let (tracks, auto_tracks, start, end, gap, content_alignment) = match axis {
        LogicalAxis::Inline => (
            &container_style.grid_template_columns,
            &container_style.grid_auto_columns,
            &child_style.grid_column_start,
            &child_style.grid_column_end,
            container_style.column_gap.clone(),
            container_style.justify_content,
        ),
        LogicalAxis::Block => (
            &container_style.grid_template_rows,
            &container_style.grid_auto_rows,
            &child_style.grid_row_start,
            &child_style.grid_row_end,
            container_style.row_gap.clone(),
            container_style.align_content,
        ),
    };
    let physical_topology = match axes.physical_axis(axis) {
        PhysicalAxis::Horizontal => columns,
        PhysicalAxis::Vertical => rows,
    };
    let logical_topology = if axes.is_reversed(axis) {
        physical_topology.reversed()
    } else {
        physical_topology.clone()
    };
    let line_offsets = logical_topology.line_offsets();
    let container_size = match axes.physical_axis(axis) {
        PhysicalAxis::Horizontal => content_area.width(),
        PhysicalAxis::Vertical => content_area.height(),
    };
    if matches!(start, css::GridPlacement::Auto) && matches!(end, css::GridPlacement::Auto) {
        // With both placement lines automatic, this axis of Grid's static
        // position rectangle is the grid container's padding-box axis.
        // Preserve it while resolving the other axis from an explicit line.
        // <https://www.w3.org/TR/css-grid-1/#abspos-items>
        return Some((0.0, container_size));
    }
    let resolved_start = grid_static_line_position(
        tracks,
        auto_tracks,
        start,
        &line_offsets,
        gap.clone(),
        content_alignment,
        container_size,
    );
    let resolved_end = grid_static_line_position(
        tracks,
        auto_tracks,
        end,
        &line_offsets,
        gap,
        content_alignment,
        container_size,
    );
    // A specified Grid line remains a valid static-position edge when the
    // opposite line is `auto`. Represent that unresolved side at the same
    // coordinate here; the abspos Grid area step expands it to the padding
    // edge. Falling back to Taffy's hypothetical item loses after-explicit
    // implicit lines because the probe does not materialize them.
    // <https://www.w3.org/TR/css-grid-1/#abspos-items>
    let start = match (resolved_start, end) {
        (Some(start), _) => start.offset,
        (None, css::GridPlacement::Auto) => resolved_end?.offset,
        (None, _) => return None,
    };
    let end = match (resolved_end, start) {
        (Some(end), _) => u16::try_from(end.line_index)
            .ok()
            .and_then(|line| {
                logical_topology.aligned_area_bounds(
                    content_alignment,
                    container_size,
                    line.checked_sub(1)?,
                    line,
                )
            })
            .map_or(end.offset, |(_, edge)| edge),
        (None, _) if matches!(end, css::GridPlacement::Auto) => start,
        (None, _) => return None,
    };
    (end >= start).then_some((start, end))
}

/// Project a logical start/end range into physical page-top rectangle edges.
#[allow(clippy::too_many_arguments)]
fn grid_project_logical_range(
    left: &mut f32,
    right: &mut f32,
    top: &mut f32,
    bottom: &mut f32,
    content_area: PageTopRect,
    start_side: PhysicalSide,
    start: f32,
    end: f32,
) {
    match start_side {
        PhysicalSide::Left => {
            *left = content_area.x() + start;
            *right = content_area.x() + end;
        }
        PhysicalSide::Right => {
            *left = content_area.x() + content_area.width() - end;
            *right = content_area.x() + content_area.width() - start;
        }
        PhysicalSide::Top => {
            *top = content_area.top_y() - start;
            *bottom = content_area.top_y() - end;
        }
        PhysicalSide::Bottom => {
            *top = content_area.bottom_y() + end;
            *bottom = content_area.bottom_y() + start;
        }
    }
}

pub(super) struct GridPositioningGeometry<'a> {
    pub(super) inner_x: f32,
    pub(super) inner_width: PhysicalContentWidth,
    pub(super) content_top: f32,
    pub(super) content_height: PhysicalContentHeight,
    pub(super) columns: &'a GridAxisTopology,
    pub(super) rows: &'a GridAxisTopology,
}

impl<'a> LayoutBuilder<'a> {
    /// Lay out an absolutely positioned grid child from its grid static position.
    ///
    /// CSS Grid says an absolutely positioned child does not participate in
    /// normal grid layout, but its static-position rectangle is derived from
    /// the grid area it would occupy:
    /// <https://www.w3.org/TR/css-grid-1/#abspos-items>.
    pub(super) fn layout_positioned_grid_child<'grid>(
        &mut self,
        child: &GridChild<'grid>,
        in_flow_children: &[GridChild<'grid>],
        context: PositionedGridStaticContext<'_>,
    ) {
        let source = context.positioning_containing_block.map_or(
            GridAbsposStaticPositionSource::ContentEdges,
            |padding_box| GridAbsposStaticPositionSource::PlacementArea { padding_box },
        );
        let row_container_size = context
            .definite_content_height
            .unwrap_or(context.content_height)
            .points();
        let content_area = PageTopRect::new(
            context.inner_x,
            context.content_top,
            context.inner_width.points(),
            row_container_size,
        );
        if matches!(source, GridAbsposStaticPositionSource::ContentEdges) {
            // Grid placement applies only when this Grid establishes the
            // actual containing block. Otherwise the static-position
            // rectangle is its content box, irrespective of grid-area.
            // <https://www.w3.org/TR/css-position-3/#staticpos-rect>
            let static_rect = grid_positioned_child_static_rect(
                source,
                content_area,
                &child.style,
                context.container_style,
            );
            self.layout_positioned_formatting_context_child(
                child,
                context.stylesheets,
                static_rect,
            );
            return;
        }
        let hypothetical_child = positioned_grid_static_probe_child(child);
        let mut hypothetical_children = Vec::with_capacity(in_flow_children.len() + 1);
        hypothetical_children.extend_from_slice(in_flow_children);
        hypothetical_children.push(hypothetical_child);
        let mut hypothetical = self
            .compute_grid_layout(
                context.container_style,
                &hypothetical_children,
                context.stylesheets,
                context.inner_width,
                context.definite_content_height,
                GridLayoutPurpose::FinalLayout,
            )
            .and_then(|layout| layout.items.into_iter().nth(in_flow_children.len()))
            .unwrap_or(GridItemLayout::new(
                GridRect::new(
                    GridPoint::new(0.0, 0.0),
                    GridSize::new(context.inner_width.points(), child.style.line_height),
                ),
                None,
            ));
        let column_start = grid_static_line_offset(
            &context.container_style.grid_template_columns,
            &context.container_style.grid_auto_columns,
            &child.style.grid_column_start,
            context.column_line_offsets,
            context.container_style.column_gap.clone(),
            context.container_style.justify_content,
            context.inner_width.points(),
        );
        let column_end = grid_static_line_offset(
            &context.container_style.grid_template_columns,
            &context.container_style.grid_auto_columns,
            &child.style.grid_column_end,
            context.column_line_offsets,
            context.container_style.column_gap.clone(),
            context.container_style.justify_content,
            context.inner_width.points(),
        );
        let column_end = match (column_start, column_end) {
            (Some(start), Some(end)) if (start - end).abs() <= 0.01 => {
                grid_static_following_line_offset(start, context.column_line_offsets).or(Some(end))
            }
            (start, end) => end.or_else(|| {
                grid_static_auto_end_line_offset(
                    start,
                    &child.style.grid_column_end,
                    context.column_line_offsets,
                    &context.container_style.grid_template_columns,
                    context.container_style.justify_content,
                    context.inner_width.points(),
                )
            }),
        };
        // A span is resolved as part of Grid placement, not as an independent
        // grid line. Reuse the hypothetical item's resolved area when an end
        // placement is a span (or named span), so the static-position
        // rectangle sees the final line offset rather than a zero-width
        // synthetic box.
        // <https://www.w3.org/TR/css-grid-1/#line-placement>
        let column_end = column_end.or_else(|| {
            hypothetical.area.and_then(|area| {
                content_aligned_grid_line_offset(
                    context.container_style.justify_content,
                    context.inner_width.points(),
                    context.column_line_offsets,
                    usize::from(area.column_end).saturating_sub(1),
                )
            })
        });
        if let Some(x) = column_start {
            hypothetical.set_axis_geometry(GridAxis::Column, x, hypothetical.width());
        }
        if let (Some(start), Some(end)) = (column_start, column_end)
            && end >= start
        {
            hypothetical.set_axis_geometry(GridAxis::Column, hypothetical.x(), end - start);
        }
        if matches!(child.style.grid_column_start, css::GridPlacement::Auto)
            && matches!(child.style.grid_column_end, css::GridPlacement::Auto)
        {
            // With both grid lines auto, the abspos static-position
            // rectangle spans the grid container's content box. It is not
            // auto-placed after the in-flow grid items.
            // <https://www.w3.org/TR/css-grid-1/#abspos-items>
            hypothetical.set_axis_geometry(GridAxis::Column, 0.0, context.inner_width.points());
        }
        if WritingModeAxes::new(
            context.container_style.writing_mode,
            context.container_style.direction,
        )
        .physical_axis(LogicalAxis::Inline)
            == PhysicalAxis::Horizontal
            && WritingModeAxes::new(
                context.container_style.writing_mode,
                context.container_style.direction,
            )
            .physical_side(LogicalSide::InlineStart)
                == PhysicalSide::Right
            && column_start.is_some()
            && column_end.is_some()
        {
            let logical_start = column_start.unwrap_or(0.0);
            let logical_end = column_end
                .unwrap_or(context.inner_width.points())
                .max(logical_start);
            hypothetical.set_axis_geometry(
                GridAxis::Column,
                context.inner_width.points() - logical_end,
                logical_end - logical_start,
            );
        }
        let row_start = grid_static_line_offset(
            &context.container_style.grid_template_rows,
            &context.container_style.grid_auto_rows,
            &child.style.grid_row_start,
            context.row_line_offsets,
            context.container_style.row_gap.clone(),
            context.container_style.align_content,
            row_container_size,
        );
        let row_end = grid_static_line_offset(
            &context.container_style.grid_template_rows,
            &context.container_style.grid_auto_rows,
            &child.style.grid_row_end,
            context.row_line_offsets,
            context.container_style.row_gap.clone(),
            context.container_style.align_content,
            row_container_size,
        );
        let row_end = match (row_start, row_end) {
            (Some(start), Some(end)) if (start - end).abs() <= 0.01 => {
                grid_static_following_line_offset(start, context.row_line_offsets).or(Some(end))
            }
            (start, end) => end.or_else(|| {
                grid_static_auto_end_line_offset(
                    start,
                    &child.style.grid_row_end,
                    context.row_line_offsets,
                    &context.container_style.grid_template_rows,
                    context.container_style.align_content,
                    row_container_size,
                )
            }),
        };
        let row_end = row_end.or_else(|| {
            hypothetical.area.and_then(|area| {
                content_aligned_grid_line_offset(
                    context.container_style.align_content,
                    row_container_size,
                    context.row_line_offsets,
                    usize::from(area.row_end).saturating_sub(1),
                )
            })
        });
        if let Some(y) = row_start {
            hypothetical.set_axis_geometry(GridAxis::Row, y, hypothetical.height());
        }
        if let (Some(start), Some(end)) = (row_start, row_end)
            && end >= start
        {
            hypothetical.set_axis_geometry(GridAxis::Row, hypothetical.y(), end - start);
        }
        if matches!(child.style.grid_row_start, css::GridPlacement::Auto)
            && matches!(child.style.grid_row_end, css::GridPlacement::Auto)
        {
            hypothetical.set_axis_geometry(GridAxis::Row, 0.0, row_container_size);
        }

        if WritingModeAxes::new(
            context.container_style.writing_mode,
            context.container_style.direction,
        )
        .swaps_physical_axes()
        {
            // `compute_grid_layout` adapts CSS Grid's logical axes to
            // Taffy's physical x/y tracks. For a positioned grid child whose
            // containing block is that grid area, select its physical area
            // through the same swapped line geometry.
            // <https://www.w3.org/TR/css-writing-modes-4/#abstract-box>
            let x_start = grid_static_line_offset(
                &context.container_style.grid_template_rows,
                &context.container_style.grid_auto_rows,
                &child.style.grid_row_start,
                context.column_line_offsets,
                context.container_style.row_gap.clone(),
                context.container_style.align_content,
                context.inner_width.points(),
            )
            .unwrap_or(0.0);
            let x_end = grid_static_line_offset(
                &context.container_style.grid_template_rows,
                &context.container_style.grid_auto_rows,
                &child.style.grid_row_end,
                context.column_line_offsets,
                context.container_style.row_gap.clone(),
                context.container_style.align_content,
                context.inner_width.points(),
            )
            .unwrap_or(context.inner_width.points())
            .max(x_start);
            let x = if matches!(
                context.container_style.writing_mode,
                WritingMode::VerticalRl | WritingMode::SidewaysRl
            ) {
                context.inner_width.points() - x_end
            } else {
                x_start
            };
            hypothetical.set_axis_geometry(GridAxis::Column, x, x_end - x_start);
            let y_start = grid_static_line_offset(
                &context.container_style.grid_template_columns,
                &context.container_style.grid_auto_columns,
                &child.style.grid_column_start,
                context.row_line_offsets,
                context.container_style.column_gap.clone(),
                context.container_style.justify_content,
                row_container_size,
            )
            .unwrap_or(0.0);
            let y_end = grid_static_line_offset(
                &context.container_style.grid_template_columns,
                &context.container_style.grid_auto_columns,
                &child.style.grid_column_end,
                context.row_line_offsets,
                context.container_style.column_gap.clone(),
                context.container_style.justify_content,
                row_container_size,
            )
            .unwrap_or(row_container_size)
            .max(y_start);
            let y = if context.container_style.direction == Direction::Rtl {
                row_container_size - y_end
            } else {
                y_start
            };
            hypothetical.set_axis_geometry(GridAxis::Row, y, y_end - y_start);
        }

        let probed_placement_area = PageTopRect::new(
            context.inner_x + hypothetical.x(),
            context.content_top - hypothetical.y(),
            hypothetical.width(),
            hypothetical.height(),
        );
        // Prefer final line geometry for directly resolvable placements. The
        // probe remains necessary for spans and incomplete line geometry, but
        // must not be allowed to reinterpret a logical Grid axis as Taffy's
        // physical x/y axis in RTL or vertical writing modes.
        let placement_area = grid_explicit_placement_area(
            context.container_style,
            &child.style,
            PageTopRect::new(
                context.inner_x,
                context.content_top,
                context.inner_width.points(),
                row_container_size,
            ),
            context.columns,
            context.rows,
        )
        .unwrap_or(probed_placement_area);
        let static_area = grid_abspos_static_position_area(
            source,
            placement_area,
            &child.style,
            context.container_style,
        );
        let static_rect = grid_positioned_child_static_rect(
            source,
            static_area,
            &child.style,
            context.container_style,
        )
        .with_static_physical_edges(
            grid_explicit_static_left_edge(&child.style, context.container_style, placement_area),
            grid_explicit_static_right_edge(&child.style, context.container_style, placement_area),
            grid_explicit_static_top_edge(&child.style, context.container_style, placement_area),
        )
        // Keep the logical Grid placement area as the alignment container.
        // `static_area` expands automatic sides to padding edges; using it
        // here would discard the explicitly selected static corner when that
        // edge lies beyond the explicit grid in an implicit track.
        .with_static_alignment(grid_abspos_static_alignment(
            placement_area,
            &child.style,
            context.container_style,
        ));
        self.layout_positioned_formatting_context_child(child, context.stylesheets, static_rect);
    }
}

/// Preserve an explicit Grid area's physical edge as the CSS Positioned
/// Layout static corner when its opposing automatic line maps to a padding
/// edge on the other side of the normalized area.
/// <https://www.w3.org/TR/css-grid-1/#abspos-items>
fn grid_explicit_static_left_edge(
    child_style: &ComputedStyle,
    container_style: &ComputedStyle,
    placement_area: PageTopRect,
) -> Option<f32> {
    let axes = WritingModeAxes::new(
        container_style.writing_mode,
        container_style.used_direction(),
    );
    match axes.physical_side(LogicalSide::InlineStart) {
        PhysicalSide::Left
            if !matches!(child_style.grid_column_start, css::GridPlacement::Auto)
                && matches!(child_style.grid_column_end, css::GridPlacement::Auto) =>
        {
            Some(placement_area.x())
        }
        _ => match axes.physical_side(LogicalSide::InlineEnd) {
            PhysicalSide::Left
                if !matches!(child_style.grid_column_end, css::GridPlacement::Auto)
                    && matches!(child_style.grid_column_start, css::GridPlacement::Auto) =>
            {
                Some(placement_area.x() + placement_area.width())
            }
            _ => None,
        },
    }
}

fn grid_explicit_static_right_edge(
    child_style: &ComputedStyle,
    container_style: &ComputedStyle,
    placement_area: PageTopRect,
) -> Option<f32> {
    let axes = WritingModeAxes::new(
        container_style.writing_mode,
        container_style.used_direction(),
    );
    match axes.physical_side(LogicalSide::InlineStart) {
        PhysicalSide::Right
            if !matches!(child_style.grid_column_start, css::GridPlacement::Auto)
                && matches!(child_style.grid_column_end, css::GridPlacement::Auto) =>
        {
            Some(placement_area.x())
        }
        _ => match axes.physical_side(LogicalSide::InlineEnd) {
            PhysicalSide::Right
                if !matches!(child_style.grid_column_end, css::GridPlacement::Auto)
                    && matches!(child_style.grid_column_start, css::GridPlacement::Auto) =>
            {
                Some(placement_area.x() + placement_area.width())
            }
            _ => None,
        },
    }
}

fn grid_explicit_static_top_edge(
    child_style: &ComputedStyle,
    container_style: &ComputedStyle,
    placement_area: PageTopRect,
) -> Option<f32> {
    let axes = WritingModeAxes::new(
        container_style.writing_mode,
        container_style.used_direction(),
    );
    match axes.physical_side(LogicalSide::BlockStart) {
        PhysicalSide::Top
            if !matches!(child_style.grid_row_start, css::GridPlacement::Auto)
                && matches!(child_style.grid_row_end, css::GridPlacement::Auto) =>
        {
            Some(placement_area.top_y())
        }
        _ => match axes.physical_side(LogicalSide::BlockEnd) {
            PhysicalSide::Top
                if !matches!(child_style.grid_row_end, css::GridPlacement::Auto)
                    && matches!(child_style.grid_row_start, css::GridPlacement::Auto) =>
            {
                Some(placement_area.top_y() - placement_area.height())
            }
            _ => None,
        },
    }
}

fn effective_grid_abspos_alignment(
    self_alignment: css::SelfAlignment,
    container_alignment: css::SelfAlignment,
) -> css::SelfAlignment {
    if self_alignment.keyword == SelfAlignmentKeyword::Auto {
        container_alignment
    } else {
        self_alignment
    }
}

/// Record Grid's fully resolved static-position defaults in the generic
/// positioned-layout alignment context. The grid area remains distinct from
/// the absolute containing block: it is only the static alignment container.
/// <https://www.w3.org/TR/css-grid-1/#abspos-items>
/// <https://drafts.csswg.org/css-align-3/#align-abspos>
fn grid_abspos_static_alignment(
    area: PageTopRect,
    child_style: &ComputedStyle,
    container_style: &ComputedStyle,
) -> AbsposStaticAlignment {
    AbsposStaticAlignment::new(
        area,
        container_style.writing_mode,
        container_style.direction,
        child_style.writing_mode,
        child_style.used_direction(),
        effective_grid_abspos_alignment(child_style.justify_self, container_style.justify_items),
        effective_grid_abspos_alignment(child_style.align_self, container_style.align_items),
    )
}

/// Resolve a grid static-position line from final layout offsets, then from
/// definite CSS track geometry if final offsets cannot cover the requested
/// line.
///
/// CSS Grid defines an abspos child's static-position rectangle from its grid
/// area. Final line offsets are preferred because they preserve used track
/// sizing, content alignment, and collapsed `auto-fit` tracks:
/// <https://www.w3.org/TR/css-grid-1/#abspos-items>.
fn grid_static_line_offset(
    tracks: &css::GridTrackList,
    auto_tracks: &css::GridAutoTrackList,
    placement: &css::GridPlacement,
    line_offsets: &[f32],
    gap: css::ComputedGap,
    content_alignment: css::ContentAlignment,
    container_size: f32,
) -> Option<f32> {
    grid_static_line_position(
        tracks,
        auto_tracks,
        placement,
        line_offsets,
        gap,
        content_alignment,
        container_size,
    )
    .map(|line| line.offset)
}

fn grid_static_line_position(
    tracks: &css::GridTrackList,
    auto_tracks: &css::GridAutoTrackList,
    placement: &css::GridPlacement,
    line_offsets: &[f32],
    gap: css::ComputedGap,
    content_alignment: css::ContentAlignment,
    container_size: f32,
) -> Option<ResolvedGridStaticLine> {
    let after_explicit_implicit_line = grid_static_placement_is_after_explicit_line(
        tracks,
        auto_tracks,
        placement,
        gap.clone(),
        container_size,
    );
    if after_explicit_implicit_line {
        // The in-flow grid has already materialized this implicit track.
        // Replaying the definite track list would re-run `align-content` on
        // an over-constrained implicit grid and move the used line.
        let from_layout = grid_layout_line_static_offset_with_inferred_gaps(
            tracks,
            auto_tracks,
            placement,
            line_offsets,
            gap.clone(),
            GridLayoutLineStaticOffsetOptions {
                content_alignment,
                container_size,
                include_inferred_gaps: false,
            },
        );
        return from_layout.or_else(|| {
            grid_line_static_position(
                tracks,
                auto_tracks,
                placement,
                gap,
                content_alignment,
                container_size,
            )
        });
    }
    // For fully definite track definitions, reconstruct the line from CSS
    // geometry first. Taffy's detailed track record can omit ordinary gutters
    // even though item placement includes them; using that record directly
    // would place an abspos item at a track's trailing edge instead of the
    // following grid line. Intrinsic and auto-repeat tracks still fall back
    // to the final layout geometry below.
    grid_line_static_position(
        tracks,
        auto_tracks,
        placement,
        gap.clone(),
        content_alignment,
        container_size,
    )
    .or_else(|| {
        grid_layout_line_static_position(
            tracks,
            auto_tracks,
            placement,
            line_offsets,
            gap,
            content_alignment,
            container_size,
        )
    })
}

fn grid_static_placement_is_after_explicit_line(
    tracks: &css::GridTrackList,
    auto_tracks: &css::GridAutoTrackList,
    placement: &css::GridPlacement,
    gap: css::ComputedGap,
    container_size: f32,
) -> bool {
    let css::GridTrackList::Tracks {
        components,
        trailing_names,
    } = tracks
    else {
        return false;
    };
    let line_names = if grid_track_list_has_auto_repeat(tracks) {
        let Some(Some(auto_repeat_count)) =
            simple_fixed_auto_repeat_count(components, gap, container_size)
        else {
            return false;
        };
        let Some(line_names) = auto_repeat_explicit_line_names(tracks, auto_repeat_count) else {
            return false;
        };
        line_names
    } else if let Some(line_names) = explicit_grid_line_names(components, trailing_names) {
        line_names
    } else {
        return false;
    };
    grid_line_static_offset_index(placement, &line_names, auto_tracks, container_size)
        .is_some_and(|line_index| line_index > line_names.len() as i32)
}

/// Resolve a grid-line static-position offset from final layout.
///
/// CSS Grid says absolutely positioned grid children do not participate in grid
/// layout, but their static-position rectangle is derived from the grid area.
/// Using the already-computed grid line offsets preserves effects such as
/// collapsed empty `auto-fit` tracks and after-explicit implicit lines already
/// created by in-flow items instead of letting a synthetic abspos probe compute
/// a partial grid:
/// <https://www.w3.org/TR/css-grid-1/#abspos-items> and
/// <https://www.w3.org/TR/css-grid-1/#auto-repeat>.
#[cfg(test)]
fn grid_layout_line_static_offset(
    tracks: &css::GridTrackList,
    auto_tracks: &css::GridAutoTrackList,
    placement: &css::GridPlacement,
    line_offsets: &[f32],
    gap: css::ComputedGap,
    content_alignment: css::ContentAlignment,
    container_size: f32,
) -> Option<f32> {
    grid_layout_line_static_position(
        tracks,
        auto_tracks,
        placement,
        line_offsets,
        gap,
        content_alignment,
        container_size,
    )
    .map(|line| line.offset)
}

fn grid_layout_line_static_position(
    tracks: &css::GridTrackList,
    auto_tracks: &css::GridAutoTrackList,
    placement: &css::GridPlacement,
    line_offsets: &[f32],
    gap: css::ComputedGap,
    content_alignment: css::ContentAlignment,
    container_size: f32,
) -> Option<ResolvedGridStaticLine> {
    grid_layout_line_static_offset_with_inferred_gaps(
        tracks,
        auto_tracks,
        placement,
        line_offsets,
        gap,
        GridLayoutLineStaticOffsetOptions {
            content_alignment,
            container_size,
            // Taffy 0.14's detailed track positions retain the used gap in
            // the topology that reaches this static-position path. Adding
            // the authored gap again would shift every later explicit line.
            include_inferred_gaps: false,
        },
    )
}

#[derive(Clone, Copy)]
struct GridLayoutLineStaticOffsetOptions {
    content_alignment: css::ContentAlignment,
    container_size: f32,
    include_inferred_gaps: bool,
}

fn grid_layout_line_static_offset_with_inferred_gaps(
    tracks: &css::GridTrackList,
    auto_tracks: &css::GridAutoTrackList,
    placement: &css::GridPlacement,
    line_offsets: &[f32],
    gap: css::ComputedGap,
    options: GridLayoutLineStaticOffsetOptions,
) -> Option<ResolvedGridStaticLine> {
    let css::GridPlacement::Line(_) = placement else {
        return None;
    };
    if grid_track_list_has_auto_repeat(tracks) {
        let auto_repeat_count = simple_fixed_auto_repeat_count(
            grid_track_list_components(tracks)?,
            gap.clone(),
            options.container_size,
        )??;
        let line_names = auto_repeat_explicit_line_names(tracks, auto_repeat_count)?;
        let auto_fill_line_offsets;
        let line_offsets = if grid_track_list_has_auto_fit(tracks) {
            line_offsets
        } else {
            let track_sizes = auto_repeat_explicit_track_sizes(
                tracks,
                auto_repeat_count,
                options.container_size,
            )?;
            let gap =
                definite_grid_gap_size(gap.clone(), layout_pt(options.container_size)).points();
            auto_fill_line_offsets = grid_line_offsets_from_track_sizes(&track_sizes, gap);
            &auto_fill_line_offsets
        };
        let line_index = grid_line_static_offset_index(
            placement,
            &line_names,
            auto_tracks,
            options.container_size,
        )?;
        let line_offsets = auto_repeat_static_line_offsets(
            line_offsets,
            &line_names,
            auto_tracks,
            line_index,
            gap,
            options.container_size,
        )?;
        let offset = content_aligned_grid_line_offset(
            options.content_alignment,
            options.container_size,
            &line_offsets.offsets,
            line_offsets.offset_index(line_index)?,
        )?;
        return Some(ResolvedGridStaticLine { line_index, offset });
    };
    let (components, trailing_names) = match tracks {
        css::GridTrackList::Tracks {
            components,
            trailing_names,
        } => (components.as_slice(), trailing_names.as_slice()),
        css::GridTrackList::None | css::GridTrackList::Subgrid { .. } => (&[][..], &[][..]),
    };
    let line_names = explicit_grid_line_names(components, trailing_names)?;
    let line_index = match placement {
        // Final grid geometry has already resolved the implicit tracks that
        // in-flow grid items created. A positive numeric line can therefore
        // use that geometry even when `grid-auto-*` is intrinsically sized and
        // cannot be reconstructed from its computed track definition alone.
        // Negative numeric lines remain relative to the explicit grid.
        css::GridPlacement::Line(line) if line.name().is_none() => {
            let index = line.index()?;
            if index > 0 {
                index
            } else {
                explicit_grid_line_index(index, i32::try_from(line_names.len()).ok()?)?
            }
        }
        _ => grid_line_static_offset_index(
            placement,
            &line_names,
            auto_tracks,
            options.container_size,
        )?,
    };
    let offset_index = usize::try_from(line_index - 1).ok()?;
    line_offsets.get(offset_index)?;
    let inferred_offsets;
    let line_offsets = if options.include_inferred_gaps {
        // Some detailed Taffy records expose track breadth accumulation while
        // reporting ordinary gutters separately. Reconstruct line coordinates
        // for those fallback paths. Fully materialized implicit grids above
        // retain their final offsets unchanged.
        let gap = definite_grid_gap_size(gap, layout_pt(options.container_size)).points();
        inferred_offsets = line_offsets
            .iter()
            .enumerate()
            .map(|(index, offset)| *offset + gap * index as f32)
            .collect::<Vec<_>>();
        &inferred_offsets
    } else {
        line_offsets
    };
    let offset = content_aligned_grid_line_offset(
        options.content_alignment,
        options.container_size,
        line_offsets,
        offset_index,
    )?;
    Some(ResolvedGridStaticLine { line_index, offset })
}

fn grid_track_list_components(
    tracks: &css::GridTrackList,
) -> Option<&[css::GridTrackListComponent]> {
    let css::GridTrackList::Tracks { components, .. } = tracks else {
        return None;
    };
    Some(components)
}

fn grid_track_list_has_auto_repeat(tracks: &css::GridTrackList) -> bool {
    let css::GridTrackList::Tracks { components, .. } = tracks else {
        return false;
    };
    components.iter().any(grid_track_component_has_auto_repeat)
}

pub(super) fn grid_track_list_has_auto_fit(tracks: &css::GridTrackList) -> bool {
    let css::GridTrackList::Tracks { components, .. } = tracks else {
        return false;
    };
    components.iter().any(grid_track_component_has_auto_fit)
}

fn grid_track_component_has_auto_repeat(component: &css::GridTrackListComponent) -> bool {
    let css::GridTrackListComponent::Repeat(_, repeat) = component else {
        return false;
    };
    matches!(
        repeat.count,
        css::GridRepeatCount::AutoFill | css::GridRepeatCount::AutoFit
    )
}

fn grid_track_component_has_auto_fit(component: &css::GridTrackListComponent) -> bool {
    let css::GridTrackListComponent::Repeat(_, repeat) = component else {
        return false;
    };
    matches!(repeat.count, css::GridRepeatCount::AutoFit)
}

fn auto_repeat_explicit_line_names(
    tracks: &css::GridTrackList,
    auto_repeat_count: u16,
) -> Option<Vec<Vec<String>>> {
    let css::GridTrackList::Tracks {
        components,
        trailing_names,
    } = tracks
    else {
        return None;
    };
    let mut lines = Vec::new();
    let mut current_line_names = Vec::new();
    collect_auto_repeat_line_names(
        components,
        auto_repeat_count,
        &mut current_line_names,
        &mut lines,
    )?;
    current_line_names.extend(trailing_names.iter().cloned());
    lines.push(current_line_names);
    Some(lines)
}

fn auto_repeat_explicit_track_sizes(
    tracks: &css::GridTrackList,
    auto_repeat_count: u16,
    container_size: f32,
) -> Option<Vec<f32>> {
    let components = grid_track_list_components(tracks)?;
    let mut sizes = Vec::new();
    collect_auto_repeat_track_sizes(components, auto_repeat_count, container_size, &mut sizes)?;
    Some(sizes)
}

fn collect_auto_repeat_track_sizes(
    components: &[css::GridTrackListComponent],
    auto_repeat_count: u16,
    container_size: f32,
    sizes: &mut Vec<f32>,
) -> Option<()> {
    for component in components {
        match component {
            css::GridTrackListComponent::Track(_, size) => {
                sizes.push(definite_auto_repeat_track_size(
                    size.clone(),
                    container_size,
                )?);
            }
            css::GridTrackListComponent::Repeat(_, repeat) => {
                let count = match repeat.count {
                    css::GridRepeatCount::Number(count) => count,
                    css::GridRepeatCount::AutoFill | css::GridRepeatCount::AutoFit => {
                        auto_repeat_count
                    }
                };
                for _ in 0..count {
                    collect_auto_repeat_track_sizes(
                        &repeat.tracks,
                        auto_repeat_count,
                        container_size,
                        sizes,
                    )?;
                }
            }
        }
    }
    Some(())
}

struct AutoRepeatStaticLineOffsets {
    first_line_index: i32,
    offsets: Vec<f32>,
}

impl AutoRepeatStaticLineOffsets {
    fn offset_index(&self, line_index: i32) -> Option<usize> {
        usize::try_from(line_index.checked_sub(self.first_line_index)?).ok()
    }
}

fn auto_repeat_static_line_offsets(
    line_offsets: &[f32],
    line_names: &[Vec<String>],
    auto_tracks: &css::GridAutoTrackList,
    line_index: i32,
    gap: css::ComputedGap,
    container_size: f32,
) -> Option<AutoRepeatStaticLineOffsets> {
    let explicit_line_count = i32::try_from(line_names.len()).ok()?;
    let before_track_count = if line_index < 1 {
        usize::try_from(1_i32.checked_sub(line_index)?).ok()?
    } else {
        0
    };
    let after_track_count = if line_index > explicit_line_count {
        usize::try_from(line_index.checked_sub(explicit_line_count)?).ok()?
    } else {
        0
    };
    let gap = definite_grid_gap_size(gap, layout_pt(container_size)).points();
    if before_track_count == 0 && after_track_count == 0 {
        return Some(AutoRepeatStaticLineOffsets {
            first_line_index: 1,
            offsets: line_offsets.to_vec(),
        });
    }

    let mut offsets = line_offsets.to_vec();
    let mut first_line_index = 1;
    if before_track_count > 0 {
        let mut expanded = Vec::with_capacity(before_track_count + offsets.len());
        let mut offset = 0.0;
        expanded.push(offset);
        for auto_index in (0..before_track_count).rev() {
            offset +=
                cycled_definite_auto_track_size_before(auto_tracks, auto_index, container_size)?;
            offset += gap;
            expanded.push(offset);
        }
        let explicit_start_offset = offset;
        expanded.extend(
            offsets
                .iter()
                .skip(1)
                .map(|line_offset| explicit_start_offset + *line_offset),
        );
        offsets = expanded;
        first_line_index = 1_i32.checked_sub(i32::try_from(before_track_count).ok()?)?;
    }
    if after_track_count > 0 {
        let mut offset = offsets.last().cloned()?;
        for auto_index in 0..after_track_count {
            // A following implicit line is after the preceding gutter and
            // track. The next gutter is before the next implicit track, not
            // part of this line's offset.
            offset += gap;
            offset +=
                cycled_definite_auto_track_size_after(auto_tracks, auto_index, container_size)?;
            offsets.push(offset);
        }
    }
    let result = AutoRepeatStaticLineOffsets {
        first_line_index,
        offsets,
    };
    result
        .offset_index(line_index)
        .and_then(|index| result.offsets.get(index))
        .cloned()?;
    Some(result)
}

fn collect_auto_repeat_line_names(
    components: &[css::GridTrackListComponent],
    auto_repeat_count: u16,
    current_line_names: &mut Vec<String>,
    lines: &mut Vec<Vec<String>>,
) -> Option<()> {
    for component in components {
        match component {
            css::GridTrackListComponent::Track(names, _) => {
                current_line_names.extend(names.iter().cloned());
                lines.push(std::mem::take(current_line_names));
            }
            css::GridTrackListComponent::Repeat(names, repeat) => {
                current_line_names.extend(names.iter().cloned());
                let count = match repeat.count {
                    css::GridRepeatCount::Number(count) => count,
                    css::GridRepeatCount::AutoFill | css::GridRepeatCount::AutoFit => {
                        auto_repeat_count
                    }
                };
                for _ in 0..count {
                    collect_auto_repeat_line_names(
                        &repeat.tracks,
                        auto_repeat_count,
                        current_line_names,
                        lines,
                    )?;
                    current_line_names.extend(repeat.trailing_names.iter().cloned());
                }
            }
        }
    }
    Some(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn content_edge_static_source_preserves_the_grid_content_rectangle() {
        let style = ComputedStyle::initial();
        let content = PageTopRect::new(12.0, 80.0, 40.0, 30.0);
        let padding = ContainingBlock::from_page_top_rect(PageTopRect::new(4.0, 92.0, 64.0, 54.0));

        assert_eq!(
            grid_abspos_static_position_area(
                GridAbsposStaticPositionSource::ContentEdges,
                content,
                &style,
                &style,
            ),
            content,
            "a Grid parent that is not the actual containing block ignores grid placement",
        );
        assert_ne!(content, padding.rect);
    }

    #[test]
    fn placement_area_auto_edges_follow_padding_box_in_vertical_rtl_grid() {
        let mut style = ComputedStyle::initial();
        style.writing_mode = WritingMode::VerticalRl;
        style.direction = Direction::Rtl;
        style.grid_column_end = css::GridPlacement::Line(css::GridLinePlacement::Number(
            std::num::NonZeroI32::new(2).unwrap(),
        ));
        style.grid_row_end = css::GridPlacement::Line(css::GridLinePlacement::Number(
            std::num::NonZeroI32::new(2).unwrap(),
        ));
        let placement = PageTopRect::new(20.0, 90.0, 30.0, 40.0);
        let padding_box =
            ContainingBlock::from_page_top_rect(PageTopRect::new(10.0, 100.0, 60.0, 80.0));

        // In vertical-rl/rtl, inline-start is physical bottom and block-start
        // is physical right. The automatic start lines therefore replace only
        // those two placement-area edges with Grid's padding edges.
        assert_eq!(
            grid_abspos_static_position_area(
                GridAbsposStaticPositionSource::PlacementArea { padding_box },
                placement,
                &style,
                &style,
            ),
            PageTopRect::new(20.0, 90.0, 50.0, 70.0),
        );
    }

    #[test]
    fn numeric_line_static_offset_includes_track_gaps() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![
                css::GridTrackListComponent::Track(
                    Vec::new(),
                    css::GridTrackSize {
                        min: css::GridMinTrackBreadth::LengthPercentage(
                            css::ComputedLengthPercentage::from_points(20.0),
                        ),
                        max: css::GridMaxTrackBreadth::LengthPercentage(
                            css::ComputedLengthPercentage::from_points(20.0),
                        ),
                    },
                ),
                css::GridTrackListComponent::Track(
                    Vec::new(),
                    css::GridTrackSize {
                        min: css::GridMinTrackBreadth::LengthPercentage(
                            css::ComputedLengthPercentage::from_points(20.0),
                        ),
                        max: css::GridMaxTrackBreadth::LengthPercentage(
                            css::ComputedLengthPercentage::from_points(20.0),
                        ),
                    },
                ),
            ],
            trailing_names: Vec::new(),
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Number(
            std::num::NonZeroI32::new(2).unwrap(),
        ));
        assert_eq!(
            grid_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                45.0,
            ),
            Some(25.0)
        );
    }

    #[test]
    fn named_line_static_offset_resolves_explicit_line_occurrences() {
        let fixed_track = css::GridTrackSize {
            min: css::GridMinTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
            max: css::GridMaxTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
        };
        let tracks = css::GridTrackList::Tracks {
            components: vec![
                css::GridTrackListComponent::Track(vec!["main".to_string()], fixed_track.clone()),
                css::GridTrackListComponent::Track(vec!["main".to_string()], fixed_track),
            ],
            trailing_names: vec!["main".to_string()],
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Named {
            name: "main".to_string(),
            occurrence: std::num::NonZeroI32::new(2),
        });
        assert_eq!(
            grid_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                45.0,
            ),
            Some(25.0)
        );
    }

    #[test]
    fn negative_numeric_line_static_offset_counts_from_explicit_grid_end() {
        let fixed_track = css::GridTrackSize {
            min: css::GridMinTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
            max: css::GridMaxTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
        };
        let tracks = css::GridTrackList::Tracks {
            components: vec![
                css::GridTrackListComponent::Track(Vec::new(), fixed_track.clone()),
                css::GridTrackListComponent::Track(Vec::new(), fixed_track),
            ],
            trailing_names: Vec::new(),
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Number(
            std::num::NonZeroI32::new(-1).unwrap(),
        ));
        assert_eq!(
            grid_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                45.0,
            ),
            Some(45.0)
        );
    }

    #[test]
    fn negative_named_line_static_offset_counts_from_explicit_grid_end() {
        let fixed_track = css::GridTrackSize {
            min: css::GridMinTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
            max: css::GridMaxTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(20.0),
            ),
        };
        let tracks = css::GridTrackList::Tracks {
            components: vec![
                css::GridTrackListComponent::Track(vec!["main".to_string()], fixed_track.clone()),
                css::GridTrackListComponent::Track(vec!["main".to_string()], fixed_track),
            ],
            trailing_names: vec!["main".to_string()],
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Named {
            name: "main".to_string(),
            occurrence: std::num::NonZeroI32::new(-1),
        });
        assert_eq!(
            grid_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                45.0,
            ),
            Some(45.0)
        );
    }

    #[test]
    fn numeric_static_offset_uses_final_collapsed_track_lines() {
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Number(
            std::num::NonZeroI32::new(3).unwrap(),
        ));
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFit,
                    tracks: vec![css::GridTrackListComponent::Track(
                        Vec::new(),
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: Vec::new(),
                },
            )],
            trailing_names: Vec::new(),
        };
        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(45.0)
        );
        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::End),
                70.0,
            ),
            Some(70.0)
        );
        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::SpaceBetween),
                70.0,
            ),
            Some(70.0)
        );
        let space_around = grid_layout_line_static_offset(
            &tracks,
            &css::GridAutoTrackList::initial(),
            &placement,
            &[0.0, 25.0, 45.0, 45.0],
            css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0)),
            css::ContentAlignment::new(css::ContentAlignmentKeyword::SpaceAround),
            70.0,
        )
        .unwrap();
        assert!(
            (space_around - 63.75).abs() < 0.001,
            "space-around should add half edge interval plus one between interval: {space_around}"
        );
        let space_evenly = grid_layout_line_static_offset(
            &tracks,
            &css::GridAutoTrackList::initial(),
            &placement,
            &[0.0, 25.0, 45.0, 45.0],
            css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0)),
            css::ContentAlignment::new(css::ContentAlignmentKeyword::SpaceEvenly),
            70.0,
        )
        .unwrap();
        assert!(
            (space_evenly - (45.0 + 25.0 / 3.0 * 2.0)).abs() < 0.001,
            "space-evenly should add one edge interval and one between interval: {space_evenly}"
        );
    }

    #[test]
    fn named_static_offset_expands_final_auto_fit_line_names() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFit,
                    tracks: vec![css::GridTrackListComponent::Track(
                        vec!["slot".to_string()],
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Named {
            name: "slot".to_string(),
            occurrence: std::num::NonZeroI32::new(3),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(45.0)
        );
    }

    #[test]
    fn named_static_offset_expands_final_auto_fill_line_names() {
        let fixed_track = css::GridTrackListComponent::Track(
            vec!["slot".to_string()],
            css::GridTrackSize {
                min: css::GridMinTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(10.0),
                ),
                max: css::GridMaxTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(10.0),
                ),
            },
        );
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFill,
                    tracks: vec![
                        fixed_track,
                        css::GridTrackListComponent::Track(
                            vec!["middle".to_string()],
                            css::GridTrackSize {
                                min: css::GridMinTrackBreadth::LengthPercentage(
                                    css::ComputedLengthPercentage::from_points(10.0),
                                ),
                                max: css::GridMaxTrackBreadth::LengthPercentage(
                                    css::ComputedLengthPercentage::from_points(10.0),
                                ),
                            },
                        ),
                    ],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Named {
            name: "middle".to_string(),
            occurrence: std::num::NonZeroI32::new(2),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &css::GridAutoTrackList::initial(),
                &placement,
                &[0.0, 15.0, 30.0, 45.0, 60.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                60.0,
            ),
            Some(45.0)
        );
    }

    #[test]
    fn named_static_offset_resolves_auto_fill_after_explicit_implicit_line() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFill,
                    tracks: vec![css::GridTrackListComponent::Track(
                        vec!["slot".to_string()],
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let auto_tracks = css::GridAutoTrackList::from_tracks(vec![css::GridTrackSize {
            min: css::GridMinTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(30.0),
            ),
            max: css::GridMaxTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(30.0),
            ),
        }])
        .expect("test grid auto-track list is non-empty");
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Named {
            name: "slot".to_string(),
            occurrence: std::num::NonZeroI32::new(4),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &auto_tracks,
                &placement,
                &[0.0, 25.0, 50.0, 70.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(105.0)
        );
    }

    #[test]
    fn named_static_offset_resolves_auto_fill_before_explicit_implicit_line() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFill,
                    tracks: vec![css::GridTrackListComponent::Track(
                        vec!["slot".to_string()],
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let auto_tracks = css::GridAutoTrackList::from_tracks(vec![
            css::GridTrackSize {
                min: css::GridMinTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(30.0),
                ),
                max: css::GridMaxTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(30.0),
                ),
            },
            css::GridTrackSize {
                min: css::GridMinTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(40.0),
                ),
                max: css::GridMaxTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(40.0),
                ),
            },
        ])
        .expect("test grid auto-track list is non-empty");
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Named {
            name: "slot".to_string(),
            occurrence: std::num::NonZeroI32::new(-4),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &auto_tracks,
                &placement,
                &[0.0, 25.0, 50.0, 70.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(0.0)
        );
    }

    #[test]
    fn named_static_offset_resolves_auto_fit_after_explicit_implicit_line() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFit,
                    tracks: vec![css::GridTrackListComponent::Track(
                        vec!["slot".to_string()],
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let auto_tracks = css::GridAutoTrackList::from_tracks(vec![css::GridTrackSize {
            min: css::GridMinTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(30.0),
            ),
            max: css::GridMaxTrackBreadth::LengthPercentage(
                css::ComputedLengthPercentage::from_points(30.0),
            ),
        }])
        .expect("test grid auto-track list is non-empty");
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Named {
            name: "slot".to_string(),
            occurrence: std::num::NonZeroI32::new(4),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &auto_tracks,
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(80.0)
        );
    }

    #[test]
    fn named_static_offset_resolves_auto_fit_before_explicit_implicit_line() {
        let tracks = css::GridTrackList::Tracks {
            components: vec![css::GridTrackListComponent::Repeat(
                Vec::new(),
                css::GridRepeat {
                    count: css::GridRepeatCount::AutoFit,
                    tracks: vec![css::GridTrackListComponent::Track(
                        vec!["slot".to_string()],
                        css::GridTrackSize {
                            min: css::GridMinTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                            max: css::GridMaxTrackBreadth::LengthPercentage(
                                css::ComputedLengthPercentage::from_points(20.0),
                            ),
                        },
                    )],
                    trailing_names: vec!["end".to_string()],
                },
            )],
            trailing_names: Vec::new(),
        };
        let auto_tracks = css::GridAutoTrackList::from_tracks(vec![
            css::GridTrackSize {
                min: css::GridMinTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(30.0),
                ),
                max: css::GridMaxTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(30.0),
                ),
            },
            css::GridTrackSize {
                min: css::GridMinTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(40.0),
                ),
                max: css::GridMaxTrackBreadth::LengthPercentage(
                    css::ComputedLengthPercentage::from_points(40.0),
                ),
            },
        ])
        .expect("test grid auto-track list is non-empty");
        let placement = css::GridPlacement::Line(css::GridLinePlacement::Named {
            name: "slot".to_string(),
            occurrence: std::num::NonZeroI32::new(-4),
        });

        assert_eq!(
            grid_layout_line_static_offset(
                &tracks,
                &auto_tracks,
                &placement,
                &[0.0, 25.0, 45.0, 45.0],
                css::ComputedGap::LengthPercentage(css::ComputedLengthPercentage::from_points(5.0),),
                css::ContentAlignment::new(css::ContentAlignmentKeyword::Start),
                70.0,
            ),
            Some(0.0)
        );
    }
}
